"""Fix acentuacao em quiz_seed.json — corrige todas as palavras sem acento."""
import json, re
from pathlib import Path

SEED_FILE = Path(__file__).parent / "quiz_seed.json"

# Mapa completo de acentos (~500 palavras)
ACCENT_MAP = {
    # → ão
    "nao": "não", "saO": "são", "Sao": "São", "sao": "são",
    "entao": "então", "estao": "estão", "tem": "têm",
    "civilizacao": "civilização", "organizacao": "organização",
    "transformacao": "transformação", "informacao": "informação",
    "educacao": "educação", "atencao": "atenção", "criacao": "criação",
    "revolucao": "revolução", "evolucao": "evolução", "producao": "produção",
    "comunicacao": "comunicação", "exploracao": "exploração",
    "geracao": "geração", "nacao": "nação", "gravacao": "gravação",
    "interpretacao": "interpretação", "implantacao": "implantação",
    "circulacao": "circulação", "navegacao": "navegação",
    "exportacao": "exportação", "importacao": "importação",
    "predacao": "predação", "adaptacao": "adaptação",
    "simulacao": "simulação", "polinizacao": "polinização",
    "fertilizacao": "fertilização", "fecundacao": "fecundação",
    "decomposicao": "decomposição", "respiração": "respiração",
    "fermentacao": "fermentação", "combustao": "combustão",
    "queimacao": "queimação", "oxidacao": "oxidação",
    "reacao": "reação", "fusao": "fusão", "tensao": "tensão",
    "profissao": "profissão", "licenciatura": "licenciatura",
    "suspensao": "suspensão", "expansao": "expansão",
    "extensao": "extensão", "dimensao": "dimensão",
    "previsao": "previsão", "decisao": "decisão",
    "precisao": "precisão", "colisao": "colisão",
    "divisao": "divisão", "invasao": "invasão",
    "missoes": "missões", "missoes": "missões",
    "expressoes": "expressões", "emissoes": "emissões",
    "transmissoes": "transmissões", "sessoes": "sessões",
    "profissoes": "profissões", "licoes": "lições",
    "cancoes": "canções", "coracoes": "corações",
    "geracoes": "gerações", "nacoes": "nações",
    "revolucoes": "revoluções", "evolucoes": "evoluções",
    "civilizacoes": "civilizações", "organizacoes": "organizações",
    "transformacoes": "transformações", "adaptacoes": "adaptações",

    # → ém, éns
    "tambem": "também", "alem": "além", "refem": "refém",
    "armazem": "armazém", "somente": "somente",
    "parabens": "parabéns", "convem": "convém",

    # → í (proparoxitonas)
    "matematica": "matemática", "fisica": "física", "quimica": "química",
    "geografia": "geografia", "filosofia": "filosofia", "biologia": "biologia",
    "astronomia": "astronomia", "tecnologia": "tecnologia",
    "robotica": "robótica", "mecanica": "mecânica",
    "eletronica": "eletrônica", "logica": "lógica",
    "musica": "música", "metrica": "métrica", "geometrica": "geométrica",
    "aritmetica": "aritmética", "algebra": "álgebra",
    "classica": "clássica", "gigantesca": "gigantesca",
    "caracteristica": "característica", "analise": "análise",
    "sintese": "síntese", "hipotese": "hipótese",
    "crise": "crise", "catastrofe": "catástrofe",
    "metodo": "método", "genero": "gênero", "numero": "número",
    "serie": "série", "especie": "espécie", "nivel": "nível",
    "simbolo": "símbolo", "ambito": "âmbito",
    "egipcio": "egípcio", "egipcia": "egípcia", "egipcios": "egípcios",
    "dinossauro": "dinossauro", "dinossauros": "dinossauros",
    "nucleo": "núcleo", "particula": "partícula",
    "molecula": "molécula", "celula": "célula",
    "atmosfera": "atmosfera", "estratégia": "estratégia",
    "tecnica": "técnica", "tecnico": "técnico", "tecnicos": "técnicos",
    "publica": "pública", "publico": "público", "publicos": "públicos",
    "critica": "crítica", "critico": "crítico", "criticos": "críticos",
    "unica": "única", "unico": "único", "unicos": "únicos",
    "ultima": "última", "ultimo": "último", "ultimos": "últimos",
    "pratica": "prática", "pratico": "prático",
    "dinamica": "dinâmica", "dinamico": "dinâmico",
    "organica": "orgânica", "organico": "orgânico",
    "eletrica": "elétrica", "eletrico": "elétrico",
    "magnetica": "magnética", "magnetico": "magnético",
    "nuclear": "nuclear", "nucleares": "nucleares",
    "linear": "linear", "lineares": "lineares",
    "periodo": "período", "seculo": "século", "seculos": "séculos",
    "inicio": "início", "medio": "médio", "proprio": "próprio",
    "propria": "própria", "proximos": "próximos",
    "proximo": "próximo", "proxima": "próxima",
    "indigena": "indígena", "indigenas": "indígenas",
    "ingles": "inglês", "inglesa": "inglesa",
    "frances": "francês", "francesa": "francesa",
    "portugues": "português", "portuguesa": "portuguesa",
    "japones": "japonês", "japonesa": "japonesa",
    "holandes": "holandês",
    "sabado": "sábado",
    "sociologia": "sociologia",
    "psicologia": "psicologia",
    "ecologia": "ecologia",
    "etimologia": "etimologia",
    "antropologia": "antropologia",
    "arqueologia": "arqueologia",
    "paleontologia": "paleontologia",
    "mineralogia": "mineralogia",
    "geologia": "geologia",
    "meteorologia": "meteorologia",
    "oceanografia": "oceanografia",
    "sismologia": "sismologia",
    "vulcanologia": "vulcanologia",
    "topografia": "topografia",
    "cartografia": "cartografia",
    "demografia": "demografia",
    "etnografia": "etnografia",
    "fotossintese": "fotossíntese",
    "biodiversidade": "biodiversidade",
    "ecossistema": "ecossistema", "ecossistemas": "ecossistemas",

    # → ê (paroxitonas terminadas em e)
    "voce": "você", "vos": "vós",

    # Países, capitais, continentes
    "Canada": "Canadá", "canada": "canadá",
    "Japao": "Japão", "japao": "japão",
    "Grecia": "Grécia", "grecia": "grécia",
    "Italia": "Itália", "italia": "itália",
    "Mexico": "México", "mexico": "méxico",
    "Africa": "África", "africa": "áfrica",
    "Africano": "Africano", "africano": "africano",
    "Asia": "Ásia", "asia": "ásia",
    "Asiatico": "Asiático", "asiatico": "asiático",
    "America": "América", "america": "américa",
    "Americano": "Americano", "americano": "americano",
    "Europeu": "Europeu", "europeu": "europeu",
    "Europa": "Europa", "europa": "europa",
    "Oceania": "Oceania", "oceania": "oceania",
    "Antartica": "Antártica", "antartica": "antártica",
    "Antartida": "Antártida", "antartida": "antártida",
    "Mausoleu": "Mausoléu", "mausoleu": "mausoléu",
    "Tumulo": "Túmulo", "tumulo": "túmulo",
    "Piramide": "Pirâmide", "piramide": "pirâmide",
    "Palacio": "Palácio", "palacio": "palácio",
    "tres": "três", "Tres": "Três",
    "Australia": "Austrália", "australia": "austrália",
    "Alemanha": "Alemanha", "alemanha": "alemanha",
    "Argentina": "Argentina", "argentina": "argentina",
    "Belgica": "Bélgica", "belgica": "bélgica",
    "Bolivia": "Bolívia", "bolivia": "bolívia",
    "Chile": "Chile", "chile": "chile",
    "Colombia": "Colômbia", "colombia": "colômbia",
    "Coreia": "Coreia", "coreia": "coreia",
    "Costa Rica": "Costa Rica",
    "Cuba": "Cuba", "cuba": "cuba",
    "Dinamarca": "Dinamarca", "dinamarca": "dinamarca",
    "Equador": "Equador", "equador": "equador",
    "Escocia": "Escócia", "escocia": "escócia",
    "Eslovaquia": "Eslováquia",
    "Eslovenia": "Eslovênia",
    "Espanha": "Espanha", "espanha": "espanha",
    "EUA": "EUA",
    "Filipinas": "Filipinas", "filipinas": "filipinas",
    "Finlandia": "Finlândia",
    "Franca": "França", "franca": "frança",
    "Gana": "Gana", "gana": "gana",
    "Holanda": "Holanda", "holanda": "holanda",
    "Hungria": "Hungria", "hungria": "hungria",
    "India": "Índia", "india": "índia",
    "Inglaterra": "Inglaterra", "inglaterra": "inglaterra",
    "Iraque": "Iraque", "iraque": "iraque",
    "Irlanda": "Irlanda", "irlanda": "irlanda",
    "Islandia": "Islândia",
    "Israel": "Israel", "israel": "israel",
    "Libia": "Líbia", "libia": "líbia",
    "Marrocos": "Marrocos", "marrocos": "marrocos",
    "Noruega": "Noruega", "noruega": "noruega",
    "Nova Zelandia": "Nova Zelândia",
    "Paraguai": "Paraguai", "paraguai": "paraguai",
    "Peru": "Peru", "peru": "peru",
    "Polonia": "Polônia", "polonia": "polônia",
    "Portugal": "Portugal", "portugal": "portugal",
    "Quenia": "Quênia",
    "Reino Unido": "Reino Unido",
    "Republica Dominicana": "República Dominicana",
    "Russia": "Rússia", "russia": "rússia",
    "Suecia": "Suécia", "suecia": "suécia",
    "Suica": "Suíça", "suica": "suíça",
    "Tailandia": "Tailândia",
    "Turquia": "Turquia", "turquia": "turquia",
    "Ucrania": "Ucrânia", "ucrania": "ucrânia",
    "Uruguai": "Uruguai", "uruguai": "uruguai",
    "Venezuela": "Venezuela", "venezuela": "venezuela",
    "Vietna": "Vietnã", "Vietna": "Vietnã",
    "Iugoslavia": "Iugoslávia",

    # Cidades (nomes acentuados)
    "Brasilia": "Brasília", "brasilia": "brasília",
    "Londres": "Londres", "londres": "londres",
    "Paris": "Paris", "paris": "paris",
    "Berlim": "Berlim", "berlim": "berlim",
    "Roma": "Roma", "roma": "roma",
    "Madri": "Madri", "madri": "madri",
    "Lisboa": "Lisboa", "lisboa": "lisboa",
    "Varsovia": "Varsóvia",
    "Viena": "Viena", "viena": "viena",
    "Praga": "Praga", "praga": "praga",
    "Budapeste": "Budapeste", "budapeste": "budapeste",
    "Atenas": "Atenas", "atenas": "atenas",
    "Cairo": "Cairo", "cairo": "cairo",
    "Moscou": "Moscou", "moscou": "moscou",
    "Pequim": "Pequim", "pequim": "pequim",
    "Tóquio": "Tóquio", "toquio": "tóquio",
    "Sidney": "Sidney", "sidney": "sidney",
    "Toronto": "Toronto", "toronto": "toronto",
    "Chicago": "Chicago", "chicago": "chicago",
    "Tóquio": "Tóquio",

    # → á, é, ó (oxitonas e monossilabos)
    "cravo": "cravo", "cre": "crê",
    "po": "pó", "pos": "pós", "ma": "má",
    "cafe": "café", "cafe": "café",
    "cha": "chá", "cha": "chá",
    "so": "só", "so": "só",
    "vo": "vô", "avo": "avô", "ava": "avó",
    "mae": "mãe", "pai": "pai",
    "irma": "irmã", "irmaos": "irmãos",
    "orgao": "órgão", "orgaos": "órgãos",

    # ã e õ
    "coracao": "coração", "coracoes": "corações",
    "pao": "pão", "paes": "pães",
    "alemao": "alemão", "alemaes": "alemães",
    "capitão": "capitão", "capitaes": "capitães",
    "cristao": "cristão", "cristaos": "cristãos",
    "ciencias": "ciências",
    "licenciatura": "licenciatura",
    "bencao": "bênção",
    "ordem": "ordem",
    "imagem": "imagem",
    "origem": "origem",
    "margem": "margem",
    "viagem": "viagem",
    "garagem": "garagem",
    "personagem": "personagem",
    "linguagem": "linguagem",
    "passagem": "passagem",
    "porcentagem": "porcentagem",
    "vantagem": "vantagem",
    "desvantagem": "desvantagem",

    # Termos históricos e científicos
    "Idade Media": "Idade Média",
    "idade media": "idade média",
    "Imperio Romano": "Império Romano",
    "imperio romano": "império romano",
    "Revolucao Industrial": "Revolução Industrial",
    "revolucao industrial": "revolução industrial",
    "Revolucao Francesa": "Revolução Francesa",
    "revolucao francesa": "revolução francesa",
    "Revolucao Russa": "Revolução Russa",
    "Guerra Fria": "Guerra Fria",
    "Segunda Guerra": "Segunda Guerra",
    "Primeira Guerra": "Primeira Guerra",
    "Imperio Otomano": "Império Otomano",
    "Imperio Bizantino": "Império Bizantino",
    "Imperio Inca": "Império Inca",
    "Imperio Asteca": "Império Asteca",
    "Imperio Persa": "Império Persa",
    "Imperio Macedonico": "Império Macedônico",
    "Imperio Mongol": "Império Mongol",
    "Imperio Britanico": "Império Britânico",
    "Imperio Espanhol": "Império Espanhol",
    "Imperio Portugues": "Império Português",
    "Antigo Egito": "Antigo Egito",
    "antigo egito": "antigo egito",
    "Idade Antiga": "Idade Antiga",
    "Idade Media": "Idade Média",
    "Idade Moderna": "Idade Moderna",
    "Idade Contemporanea": "Idade Contemporânea",
    "Baixa Idade Media": "Baixa Idade Média",
    "Alta Idade Media": "Alta Idade Média",
    "Renascimento": "Renascimento",
    "Iluminismo": "Iluminismo",
    "Feudalismo": "Feudalismo",
    "Capitalismo": "Capitalismo",
    "Socialismo": "Socialismo",
    "Comunismo": "Comunismo",
    "Democracia": "Democracia",
    "Ditadura": "Ditadura",
    "Republica": "República",
    "Monarquia": "Monarquia",
    "Oligarquia": "Oligarquia",
    "Teocracia": "Teocracia",
    "Aristocracia": "Aristocracia",
    "Plutocracia": "Plutocracia",
    "Burocracia": "Burocracia",
    "Meritocracia": "Meritocracia",
    "Tecnocracia": "Tecnocracia",
    "Autocracia": "Autocracia",

    # Geografia
    "Amazonia": "Amazônia", "amazonia": "amazônia",
    "Sertao": "Sertão", "sertao": "sertão",
    "Pantanal": "Pantanal", "pantanal": "pantanal",
    "Cerrado": "Cerrado", "cerrado": "cerrado",
    "Caucaso": "Cáucaso", "caucaso": "cáucaso",
    "Himalaia": "Himalaia", "himalaia": "himalaia",
    "Andes": "Andes", "andes": "andes",
    "Alpes": "Alpes", "alpes": "alpes",
    "Sahara": "Saara", "sahara": "saara",
    "Atacama": "Atacama", "atacama": "atacama",
    "Patagonia": "Patagônia",
    "Siberia": "Sibéria", "siberia": "sibéria",
    "Groenlandia": "Groenlândia",
    "Islandia": "Islândia",
    "Madagascar": "Madagascar", "madagascar": "madagascar",
    "Caribe": "Caribe", "caribe": "caribe",
    "Mediterraneo": "Mediterrâneo",
    "Atlantico": "Atlântico", "atlantico": "atlântico",
    "Pacifico": "Pacífico", "pacifico": "pacífico",
    "Indico": "Índico", "indico": "índico",
    "Artico": "Ártico", "artico": "ártico",
    "Antartico": "Antártico", "antartico": "antártico",
    "Equador": "Equador", "equador": "equador",
    "Tropico": "Trópico", "tropico": "trópico",
    "Mesoamerica": "Mesoamérica",
    "America do Sul": "América do Sul",
    "America do Norte": "América do Norte",
    "America Central": "América Central",
    "America Latina": "América Latina",
    "America Anglo-Saxonica": "América Anglo-Saxônica",

    # → ç
    "cancaO": "canção", "cancao": "canção",
    "licao": "lição", "licoes": "lições",
    "nacional": "nacional", "nacionais": "nacionais",
    "internacional": "internacional",
    "educacional": "educacional",
    "profissional": "profissional",
    "tradicional": "tradicional",
    "constitucional": "constitucional",
    "institucional": "institucional",
    "operacional": "operacional",
    "emocional": "emocional",
    "racional": "racional",
    "nacionalidade": "nacionalidade",
    "natural": "natural",
    "cultura": "cultura",
    "cultural": "cultural",
    "agricultura": "agricultura",
    "arquitetura": "arquitetura",
    "estrutura": "estrutura",
    "infraestrutura": "infraestrutura",
    "literatura": "literatura",
    "abertura": "abertura",
    "cobertura": "cobertura",
    "descoberta": "descoberta",
    "descoberto": "descoberto",
    "nocoes": "noções",

    # → acentos diversos
    "heroi": "herói", "herois": "heróis",
    "papel": "papel", "papeis": "papéis",
    "aneis": "anéis", "carnavais": "carnavais",
    "funis": "funis", "funil": "funil",
    "juvenil": "juvenil",
    "infantil": "infantil",
    "civil": "civil",
    "automatico": "automático", "automatica": "automática",
    "hidraulica": "hidráulica",
    "termica": "térmica", "termico": "térmico",
    "acustica": "acústica", "acustico": "acústico",
    "plastico": "plástico", "plastica": "plástica",
    "metalico": "metálico", "metálica": "metálica",
    "ceramico": "cerâmico", "ceramica": "cerâmica",
    "alcalino": "alcalino",
    "acido": "ácido", "acida": "ácida",
    "basico": "básico", "basica": "básica",
    "neutro": "neutro", "neutra": "neutra",
    "ionico": "iônico", "ionica": "iônica",
    "covalente": "covalente",
    "metal": "metal", "metais": "metais",
    "liquido": "líquido", "liquida": "líquida",
    "gasoso": "gasoso", "gasosa": "gasosa",
    "solido": "sólido", "solida": "sólida",
    "fenomeno": "fenômeno", "fenomenos": "fenômenos",
    "indice": "índice", "indices": "índices",
    "matriz": "matriz", "matrizes": "matrizes",
    "código": "código", "codigo": "código",
    "decodigo": "decodificação",
    "protocolo": "protocolo",
    "dialeto": "dialeto",
    "idioma": "idioma",
    "linguagem": "linguagem",
    "alfabeto": "alfabeto",
    "gramatica": "gramática",
    "ortografia": "ortografia",
    "semantica": "semântica",
    "fonetica": "fonética",
    "sintaxe": "sintaxe",
    "morfologia": "morfologia",
    "lexico": "léxico",
    "vocabulario": "vocabulário",
    "dicionario": "dicionário",
    "enciclopedia": "enciclopédia",
    "biblioteca": "biblioteca",
    "hemeroteca": "hemeroteca",
    "pinacoteca": "pinacoteca",
    "discoteca": "discoteca",
    "videoteca": "videoteca",

    # Categorias
    "Misterios": "Mistérios", "misterios": "mistérios",
    "Historia": "História", "historia": "história",
    "Ciencia": "Ciência", "ciencia": "ciência",
    "Tecnologia": "Tecnologia", "tecnologia": "tecnologia",
    "Geografia": "Geografia", "geografia": "geografia",
    "Filosofia": "Filosofia", "filosofia": "filosofia",
    "Economia": "Economia", "economia": "economia",
    "Cultura": "Cultura", "cultura": "cultura",
    "Arte": "Arte", "arte": "arte",
    "Culinaria": "Culinária", "culinaria": "culinária",
    "Curiosidades": "Curiosidades", "curiosidades": "curiosidades",
    "Esportes": "Esportes", "esportes": "esportes",

    # Adjetivos pátrios
    "indigena": "indígena", "indigenas": "indígenas",
    "europeia": "europeia", "europeu": "europeu",
    "asiatico": "asiático", "asiatica": "asiática",
    "africano": "africano", "africana": "africana",
    "americano": "americano", "americana": "americana",
    "brasileiro": "brasileiro", "brasileira": "brasileira",
    "portugues": "português", "portuguesa": "portuguesa",
    "frances": "francês", "francesa": "francesa",
    "ingles": "inglês", "inglesa": "inglesa",
    "espanhol": "espanhol", "espanhola": "espanhola",
    "italiano": "italiano", "italiana": "italiana",
    "alemaO": "alemão", "alemao": "alemão",
    "japones": "japonês", "japonesa": "japonesa",
    "chines": "chinês", "chinesa": "chinesa",
    "russo": "russo", "russa": "russa",
    "canadense": "canadense",
    "mexicano": "mexicano", "mexicana": "mexicana",
    "argentino": "argentino", "argentina": "argentina",
    "chileno": "chileno", "chilena": "chilena",
    "peruano": "peruano", "peruana": "peruana",
    "uruguaio": "uruguaio", "uruguaia": "uruguaia",
    "paraguaio": "paraguaio", "paraguaia": "paraguaia",
    "boliviano": "boliviano", "boliviana": "boliviana",
    "venezuelano": "venezuelano", "venezuelana": "venezuelana",
    "colombiano": "colombiano", "colombiana": "colombiana",
    "egipcio": "egípcio", "egipcia": "egípcia",
    "grego": "grego", "grega": "grega",
    "romano": "romano", "romana": "romana",
    "arabe": "árabe",
    "judeu": "judeu", "judia": "judia",
    "persa": "persa",
    "turco": "turco", "turca": "turca",
    "hindu": "hindu",
    "celta": "celta",
    "viking": "viking",
    "inca": "inca", "incas": "incas",
    "asteca": "asteca", "astecas": "astecas",
    "maia": "maia", "maias": "maias",
    "tupi": "tupi", "tupis": "tupis",
    "guarani": "guarani",
    "iorkuba": "ioruba",

    # Verbos comuns
    "existe": "existe",
    "existem": "existem",
    "inclui": "inclui",
    "continua": "continua",
    "utiliza": "utiliza",
    "realiza": "realiza",
    "analisa": "analisa",
    "sintetiza": "sintetiza",
    "categoriza": "categoriza",
    "caracteriza": "caracteriza",
    "simboliza": "simboliza",
    "representa": "representa",
    "identifica": "identifica",
    "classifica": "classifica",
    "modifica": "modifica",
    "amplifica": "amplifica",
    "unifica": "unifica",
    "verifica": "verifica",
    "comunica": "comunica",
    "fabrica": "fabrica",
    "publica": "publica",
    "dedica": "dedica",
    "aplica": "aplica",
    "explica": "explica",
    "multiplica": "multiplica",
    "simplifica": "simplifica",
    "intensifica": "intensifica",
    "diversifica": "diversifica",
    "especifica": "especifica",
    "qualifica": "qualifica",
    "quantifica": "quantifica",

    # Varias
    "atmosferico": "atmosférico", "atmosferica": "atmosférica",
    "oceanico": "oceânico", "oceanica": "oceânica",
    "vulcanico": "vulcânico", "vulcanica": "vulcânica",
    "sismico": "sísmico", "sismica": "sísmica",
    "tectonico": "tectônico", "tectonica": "tectônica",
    "climatico": "climático", "climatica": "climática",
    "paleolitico": "paleolítico",
    "neolitico": "neolítico",
    "mesolitico": "mesolítico",
    "paleozoico": "paleozoico",
    "mesozoico": "mesozoico",
    "cenozoico": "cenozoico",
    "pre-historico": "pré-histórico",
    "pre-historica": "pré-histórica",
    "pos-moderno": "pós-moderno",
    "pos-moderna": "pós-moderna",
    "pre-colombiano": "pré-colombiano",
    "pre-colombiana": "pré-colombiana",
    "pos-guerra": "pós-guerra",
    "pre-requisito": "pré-requisito",
    "bem-vindo": "bem-vindo",
    "bem-vinda": "bem-vinda",
    "dia-a-dia": "dia a dia",
    "mais": "mais",
    "menos": "menos",
    "muito": "muito", "muita": "muita",
    "pouco": "pouco", "pouca": "pouca",
    "grande": "grande", "grandes": "grandes",
    "pequeno": "pequeno", "pequena": "pequena",
    "melhor": "melhor", "melhores": "melhores",
    "pior": "pior", "piores": "piores",
    "maior": "maior", "maiores": "maiores",
    "menor": "menor", "menores": "menores",
    "superior": "superior", "inferior": "inferior",
    "anterior": "anterior", "posterior": "posterior",
    "interior": "interior", "exterior": "exterior",
    "primeiro": "primeiro", "primeira": "primeira",
    "segundo": "segundo", "segunda": "segunda",
    "terceiro": "terceiro", "terceira": "terceira",
    "ultimo": "último", "ultima": "última",
    "penultimo": "penúltimo", "penultima": "penúltima",
    "proximo": "próximo", "proxima": "próxima",
    "proprio": "próprio", "propria": "própria",
    "alheio": "alheio", "alheia": "alheia",
    "estrangeiro": "estrangeiro", "estrangeira": "estrangeira",
    "verdadeiro": "verdadeiro", "verdadeira": "verdadeira",
    "falso": "falso", "falsa": "falsa",
    "correto": "correto", "correta": "correta",
    "errado": "errado", "errada": "errada",
    "exato": "exato", "exata": "exata",
    "preciso": "preciso", "precisa": "precisa",
    "completo": "completo", "completa": "completa",
    "vazio": "vazio", "vazia": "vazia",
    "cheio": "cheio", "cheia": "cheia",
    "unico": "único", "unica": "única",
    "raro": "raro", "rara": "rara",
    "comum": "comum", "comuns": "comuns",
    "frequente": "frequente", "frequentes": "frequentes",
    "raro": "raro", "rara": "rara",
    "antigo": "antigo", "antiga": "antiga",
    "moderno": "moderno", "moderna": "moderna",
    "contemporaneo": "contemporâneo", "contemporanea": "contemporânea",
    "futuro": "futuro", "futura": "futura",
    "passado": "passado", "passada": "passada",
    "presente": "presente", "presentes": "presentes",
    "eterno": "eterno", "eterna": "eterna",
    "temporario": "temporário", "temporaria": "temporária",
    "permanente": "permanente",
    "definitivo": "definitivo", "definitiva": "definitiva",
    "provisorio": "provisório", "provisoria": "provisória",
    "inicial": "inicial", "iniciais": "iniciais",
    "final": "final", "finais": "finais",
    "principal": "principal", "principais": "principais",
    "secundario": "secundário", "secundaria": "secundária",
    "essencial": "essencial", "essenciais": "essenciais",
    "basico": "básico", "basica": "básica",
    "avancado": "avançado", "avancada": "avançada",
    "intermediario": "intermediário", "intermediaria": "intermediária",
    "fundamental": "fundamental",
    "elementar": "elementar",
    "superficial": "superficial",
    "profundo": "profundo", "profunda": "profunda",
    "raso": "raso", "rasa": "rasa",
    "largo": "largo", "larga": "larga",
    "estreito": "estreito", "estreita": "estreita",
    "grosso": "grosso", "grossa": "grossa",
    "fino": "fino", "fina": "fina",
    "duro": "duro", "dura": "dura",
    "mole": "mole",
    "leve": "leve",
    "pesado": "pesado", "pesada": "pesada",
    "rapido": "rápido", "rapida": "rápida",
    "lento": "lento", "lenta": "lenta",
    "veloz": "veloz",
    "forte": "forte", "fortes": "fortes",
    "fraco": "fraco", "fraca": "fraca",
    "resistente": "resistente",
    "fragil": "frágil", "frageis": "frágeis",
    "solido": "sólido", "solida": "sólida",
    "liquido": "líquido", "liquida": "líquida",
    "gasoso": "gasoso", "gasosa": "gasosa",
    "duro": "duro", "dura": "dura",
    "macio": "macio", "macia": "macia",
    "áspero": "áspero", "aspera": "áspera",
    "liso": "liso", "lisa": "lisa",
    "rugoso": "rugoso", "rugosa": "rugosa",
    "curvo": "curvo", "curva": "curva",
    "reto": "reto", "reta": "reta",
    "inclinado": "inclinado", "inclinada": "inclinada",
    "horizontal": "horizontal",
    "vertical": "vertical",
    "paralelo": "paralelo", "paralela": "paralela",
    "perpendicular": "perpendicular",
    "diagonal": "diagonal",
    "circular": "circular",
    "quadrado": "quadrado", "quadrada": "quadrada",
    "triangular": "triangular",
    "retangular": "retangular",
    "esferico": "esférico", "esferica": "esférica",
    "cilindrico": "cilíndrico", "cilindrica": "cilíndrica",
    "conico": "cônico", "conica": "cônica",
    "piramidal": "piramidal",
    "cubico": "cúbico", "cubica": "cúbica",
    "hexagonal": "hexagonal",
    "octogonal": "octogonal",
    "poligonal": "poligonal",
    "simetrico": "simétrico", "simetrica": "simétrica",
    "assimetrico": "assimétrico", "assimetrica": "assimétrica",
    "proporcional": "proporcional",
    "equivalente": "equivalente",
    "constante": "constante",
    "variavel": "variável", "variaveis": "variáveis",
    "continua": "contínua", "continuo": "contínuo",
    "discreto": "discreto", "discreta": "discreta",
    "alternado": "alternado", "alternada": "alternada",
    "aleatorio": "aleatório", "aleatoria": "aleatória",
    "deterministico": "determinístico",
    "estocastico": "estocástico",
    "caotico": "caótico", "caotica": "caótica",

    # Mais terminacoes comuns
    "dade": "dade",
    "bilidade": "bilidade",
    "abilidade": "abilidade",
    "capacidade": "capacidade",
    "velocidade": "velocidade",
    "gravidade": "gravidade",
    "atividade": "atividade",
    "quantidade": "quantidade",
    "qualidade": "qualidade",
    "dificuldade": "dificuldade",
    "facilidade": "facilidade",
    "simplicidade": "simplicidade",
    "complexidade": "complexidade",
    "diversidade": "diversidade",
    "universidade": "universidade",
    "cidade": "cidade",
    "sociedade": "sociedade",
    "variedade": "variedade",
    "humanidade": "humanidade",
    "oportunidade": "oportunidade",
    "finalidade": "finalidade",
    "moralidade": "moralidade",
    "legalidade": "legalidade",
    "igualdade": "igualdade",
    "liberdade": "liberdade",
    "fraternidade": "fraternidade",
    "solidariedade": "solidariedade",
    "responsabilidade": "responsabilidade",
    "possibilidade": "possibilidade",
    "probabilidade": "probabilidade",
    "viabilidade": "viabilidade",
    "estabilidade": "estabilidade",
    "instabilidade": "instabilidade",
    "vulnerabilidade": "vulnerabilidade",
    "sustentabilidade": "sustentabilidade",
    "rentabilidade": "rentabilidade",
    "lucratividade": "lucratividade",
    "produtividade": "produtividade",
    "criatividade": "criatividade",
    "atividade": "atividade",
    "passividade": "passividade",
    "positividade": "positividade",
    "negatividade": "negatividade",
    "sensibilidade": "sensibilidade",
    "insensibilidade": "insensibilidade",
    "flexibilidade": "flexibilidade",
    "inflexibilidade": "inflexibilidade",
    "visibilidade": "visibilidade",
    "invisibilidade": "invisibilidade",
    "audibilidade": "audibilidade",
    "legibilidade": "legibilidade",
    "confiabilidade": "confiabilidade",
    "durabilidade": "durabilidade",
    "estabilidade": "estabilidade",
    "instabilidade": "instabilidade",
    "rentabilidade": "rentabilidade",
    "lucratividade": "lucratividade",

    # Outros
    "ideia": "ideia",
    "assembleia": "assembleia",
    "baleia": "baleia",
    "teto": "teto",
    "projeto": "projeto",
    "objeto": "objeto",
    "sujeito": "sujeito",
    "respeito": "respeito",
    "aspecto": "aspecto",
    "conceito": "conceito",
    "preceito": "preceito",
    "ponto": "ponto",
    "pontos": "pontos",
    "fato": "fato",
    "fatos": "fatos",
    "lado": "lado",
    "modo": "modo",
    "caso": "caso",
    "passo": "passo",
    "mundo": "mundo",
    "fundo": "fundo",
    "campo": "campo",
    "tempo": "tempo",
    "corpo": "corpo",
    "espaco": "espaço",
    "poco": "poço",
    "piscina": "piscina",
    "vizinhança": "vizinhança",

    # Complementos
    "atomo": "átomo", "atomos": "átomos",
    "eletron": "elétron", "eletrons": "elétrons",
    "proton": "próton", "protons": "prótons",
    "neutron": "nêutron", "neutrons": "nêutrons",
    "foton": "fóton", "fotons": "fótons",
    "ion": "íon", "ions": "íons",
    "morfologia": "morfologia",
    "fisiologia": "fisiologia",
    "anatomia": "anatomia",
    "histologia": "histologia",
    "citologia": "citologia",
    "embriologia": "embriologia",
    "genetica": "genética",
    "evolucao": "evolução",
    "taxonomia": "taxonomia",
    "sistematica": "sistemática",
    "filogenia": "filogenia",
    "ontogenia": "ontogenia",
    "ecossistema": "ecossistema",
    "biosfera": "biosfera",
    "litosfera": "litosfera",
    "hidrosfera": "hidrosfera",
    "atmosfera": "atmosfera",
    "estratosfera": "estratosfera",
    "troposfera": "troposfera",
    "mesosfera": "mesosfera",
    "termosfera": "termosfera",
    "exosfera": "exosfera",
    "biodiversidade": "biodiversidade",
    "biologia": "biologia",
    "botanica": "botânica",
    "zoologia": "zoologia",
    "micologia": "micologia",
    "virologia": "virologia",
    "bacteriologia": "bacteriologia",
    "parasitologia": "parasitologia",
    "imunologia": "imunologia",
    "farmacologia": "farmacologia",
    "toxicologia": "toxicologia",
    "patologia": "patologia",
    "epidemiologia": "epidemiologia",
    "bioquimica": "bioquímica",
    "biofisica": "biofísica",
    "biomedicina": "biomedicina",
    "biotecnologia": "biotecnologia",
    "bioetica": "bioética",
    "bioaumento": "bioaumento",
    "biomimetica": "biomimética",
    "biodinamica": "biodinâmica",
}

# Remove identity entries (key == val) — they do nothing
ACCENT_MAP = {k: v for k, v in ACCENT_MAP.items() if k != v}

# Build single regex pattern (longest words first)
sorted_keys = sorted(ACCENT_MAP.keys(), key=lambda k: (-len(k), k))
PATTERN = re.compile(r'\b(' + '|'.join(re.escape(k) for k in sorted_keys) + r')\b')

def fix_text(text):
    """Aplica correcao de acentos a um texto (single-pass regex)."""
    if not text:
        return text
    return PATTERN.sub(lambda m: ACCENT_MAP[m.group(1)], text)

def fix_question(q):
    """Corrige todos os campos textuais de uma pergunta."""
    if "question" in q:
        q["question"] = fix_text(q["question"])
    if "alternatives" in q:
        q["alternatives"] = [fix_text(a) for a in q["alternatives"]]
    if "explanation" in q:
        q["explanation"] = fix_text(q["explanation"])
    if "category" in q:
        q["category"] = fix_text(q["category"])
    return q

def main():
    print(f"Lendo {SEED_FILE} ...")
    with open(SEED_FILE, encoding="utf-8") as f:
        data = json.load(f)

    print(f"Total de perguntas: {len(data)}")
    total_fixes = 0

    for i, q in enumerate(data):
        original = json.dumps(q, ensure_ascii=False)
        q = fix_question(q)
        fixed = json.dumps(q, ensure_ascii=False)
        if original != fixed:
            total_fixes += 1
            if total_fixes <= 5:
                print(f"\n  Exemplo #{total_fixes}:")
                print(f"  ANTES:  {original[:120]}")
                print(f"  DEPOIS: {fixed[:120]}")

    with open(SEED_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"\n{total_fixes} perguntas corrigidas.")
    print("Arquivo salvo.")

if __name__ == "__main__":
    main()
