import json, random
from pathlib import Path

OUT_DIR = Path(__file__).parent
questions = []

def add(cat, qs):
    existing = {q["question"] for q in questions}
    for q, alt, corr, exp in qs:
        if q not in existing:
            questions.append({"question": q, "alternatives": alt, "correct": corr, "explanation": exp, "category": cat})
            existing.add(q)

# ============ ALL 10 CATEGORIES ============

add("Misterios", [
    ("Qual navio desapareceu misteriosamente no Triangulo das Bermudas em 1918?", ["USS Cyclops", "Titanic", "Lusitania", "Andrea Doria"], 0, "O USS Cyclops desapareceu sem deixar vestigios com 309 pessoas."),
    ("O que sao as Linhas de Nazca?", ["Geoglifos no deserto do Peru", "Ruinas maias", "Piramides egipcias", "Murais chineses"], 0, "Geoglifos gigantes no deserto de Nazca, Peru."),
    ("O que e o Efeito Mandela?", ["Memoria falsa compartilhada", "Doenca neurodegenerativa", "Experimento", "Fenomeno natural"], 0, "Fenomeno onde muitas pessoas compartilham a mesma memoria falsa."),
    ("Qual criatura lendaria habitaria o Lago Ness?", ["Nessie", "Chupacabra", "Yeti", "Lobisomem"], 0, "Suposto monstro aquatico no Lago Ness na Escocia."),
    ("O que e a Pedra de Roseta?", ["Pedra com tres escritas", "Pedra preciosa", "Monumento", "Templo"], 0, "Pedra que permitiu decifrar os hieroglifos egipcios."),
    ("O que aconteceu na Passagem de Dyatlov?", ["Nove morreram misteriosamente", "Avalanche", "Incendio", "Ataque"], 0, "Nove excursionistas morreram nos montes Urais em 1959."),
    ("O que e o Triangulo das Bermudas?", ["Regiao de desaparecimentos", "Ilha paradisiaca", "Base militar", "Recife"], 0, "Regiao no Atlantico Norte com desaparecimentos misteriosos."),
    ("O que sao os circulos nas plantacoes?", ["Padroes geometricos misteriosos", "Cultivo organico", "Marcas de animais", "Sinais de radar"], 0, "Padroes que aparecem misteriosamente em plantacoes pelo mundo."),
    ("O que e o Mothman?", ["Criatura alada lendaria", "Inseto gigante", "Ave migratoria", "Mutacao"], 0, "Criatura alada avistada em Point Pleasant, EUA."),
    ("O que e o Yeti?", ["Criatura lendaria do Himalaia", "Urso polar", "Macaco", "Espirito"], 0, "Suposto primata gigante que viveria no Himalaia."),
    ("O que e o Chupacabra?", ["Criatura que ataca animais", "Lenda urbana", "Cachorro selvagem", "Lobo"], 0, "Criatura lendaria que supostamente ataca animais."),
    ("Onde fica Stonehenge?", ["Inglaterra", "Escocia", "Irlanda", "Franca"], 0, "Monumento pre-historico em Salisbury, Inglaterra."),
    ("O que e a Atlantida?", ["Continente lendario submerso", "Cidade grega", "Ilha vulcanica", "Templo"], 0, "Continente lendario que teria afundado no oceano."),
    ("O que e o Zodiaco?", ["Cinturao de constelacoes", "Mapa astral", "Crenca", "Calendario"], 0, "Faixa celeste dividida em 12 signos ao longo da ecliptica."),
    ("O que e a Numerologia?", ["Estudo do significado dos numeros", "Ciencia", "Ramo da matematica", "Contagem"], 0, "Crenca na relacao misticas entre numeros e eventos."),
    ("O que e o Golem?", ["Criatura de barro do folclore", "Robo medieval", "Espirito", "Deus pagao"], 0, "Ser artificial de barro da mitologia judaica."),
    ("O que sao os OVNIs?", ["Objetos voadores nao identificados", "Aeronaves", "Fenomenos naturais", "Satelites"], 0, "Objetos voadores de origem nao identificada."),
    ("O que e o Poltergeist?", ["Fenomeno de objetos se movendo", "Assombracao", "Espirito bondoso", "Sonho"], 0, "Fenomeno paranormal com movimentacao de objetos."),
    ("O que e a Mula sem Cabeca?", ["Figura do folclore brasileiro", "Animal", "Fantasma", "Ave noturna"], 0, "Figura do folclore: mula que solta fogo pelo nariz."),
    ("O que e o Curupira?", ["Protetor das florestas", "Espirito da agua", "Fantasma", "Deus"], 0, "Figura do folclore brasileiro com pes virados para tras."),
    ("O que e o Saci Perere?", ["Menino de uma perna so", "Duende", "Passaro", "Peixe"], 0, "Personagem do folclore brasileiro que fuma cachimbo."),
    ("O que e o Boto Cor-de-Rosa?", ["Lenda do boto que vira homem", "Peixe", "Deus do rio", "Protetor"], 0, "Lenda amazonica de um boto que vira homem sedutor."),
    ("O que e o Lobisomem?", ["Homem que vira lobo", "Cachorro", "Espirito", "Fantasma"], 0, "Criatura que se transforma em lobo na lua cheia."),
    ("O que e o Vampiro?", ["Criatura que bebe sangue", "Morcego", "Espirito", "Assombracao"], 0, "Criatura lendaria que se alimenta de sangue."),
    ("O que e a Caveira de Cristal?", ["Artefato misterioso", "Pedra preciosa", "Ferramenta", "Joia"], 0, "Supostos cranios de cristal com poderes misteriosos."),
    ("O que e o Codigo Voynich?", ["Manuscrito indecifravel", "Cifra militar", "Livro sagrado", "Texto"], 0, "Manuscrito ilustrado em lingua desconhecida."),
    ("O que foi o Incidente de Tunguska?", ["Explosao misteriosa na Siberia", "Meteoro", "Ataque alien", "Vulcao"], 0, "Explosao em 1908 na Siberia, possivelmente um meteoro."),
    ("O que e o Holandes Voador?", ["Navio fantasma lendario", "Pirata", "Ilha misteriosa", "Tesouro"], 0, "Navio fantasma que aparece no Cabo da Boa Esperanca."),
    ("O que e o Kraken?", ["Lula gigante lendaria", "Polvo", "Baleia", "Serpente"], 0, "Monstro marinho lendario que atacava navios."),
    ("O que e o Fenix?", ["Passaro que renasce das cinzas", "Ave mitologica", "Falcao", "Corvo"], 0, "Passaro mitologico que renasce das proprias cinzas."),
    ("O que e o Lago Hillier?", ["Lago rosa na Australia", "Lago vulcanico", "Lago doce", "Lago salgado"], 0, "Lago de cor rosa intensa na Australia."),
    ("O que e o Misterio de Oak Island?", ["Tesouro enterrado em ilha", "Base pirata", "Cemiterio", "Forte"], 0, "Ilha no Canada com suposto tesouro enterrado."),
    ("O que e o Misterio de DB Cooper?", ["Sequestrador de aviao sumido", "Pirata aereo", "Espiao", "Piloto"], 0, "Homem que sequestrou um aviao em 1971 e sumiu."),
    ("O que e o Caso Somerton?", ["Morte misteriosa na Australia", "Crime", "Suicidio", "Acidente"], 0, "Homem encontrado morto na praia de Somerton em 1948."),
    ("O que e a Casa Winchester?", ["Casa mal-assombrada", "Mansao historica", "Castelo", "Forte"], 0, "Mansao construida por 38 anos para acalmar espiritos."),
    ("O que e o Farol de Eilean Mor?", ["Farol onde faroleiros sumiram", "Farol escoces", "Torre", "Estacao"], 0, "Farol nas ilhas Flannan onde faroleiros desapareceram."),
    ("O que e o Navio Mary Celeste?", ["Navio encontrado sem tripulacao", "Pirata", "Navio de guerra", "Submarino"], 0, "Navio encontrado a deriva sem tripulacao em 1872."),
    ("O que sao as Bolas de Pedra da Costa Rica?", ["Esferas perfeitas de pedra", "Meteoritos", "Ovos", "Fosseis"], 0, "Esferas de pedra quase perfeitas na Costa Rica."),
    ("O que sao os Geoglifos de Atacama?", ["Figuras no deserto chileno", "Ruinas", "Murais", "Esculturas"], 0, "Figuras gigantes no deserto do Atacama, Chile."),
    ("O que sao as Ruinas de Yonaguni?", ["Estruturas submersas no Japao", "Templos", "Formacoes", "Recifes"], 0, "Formacoes rochosas submersas que parecem ruinas."),
    ("O que e o Jersey Devil?", ["Criatura alada de Nova Jersey", "Mutante", "Urso", "Ave"], 0, "Criatura lendaria que assombra pinheirais de Nova Jersey."),
    ("O que foi o desaparecimento de Amelia Earhart?", ["Piloto desaparecida no Pacifico", "Acidente", "Sequestro", "Fuga"], 0, "Aviadora desapareceu em 1937 durante voo ao redor do mundo."),
    ("O que e o Enigma da Ilha de Páscoa?", ["Estatuas Moai misteriosas", "Vulcao", "Templo", "Fortaleza"], 0, "Ilha remota com enormes estatuas de pedra."),
    ("O que foi a Biblioteca de Alexandria?", ["Biblioteca perdida da antiguidade", "Templo", "Colecao", "Universidade"], 0, "Uma das maiores bibliotecas da antiguidade, destruida."),
    ("O que sao os Jardins Suspensos da Babilonia?", ["Maravilha do mundo antigo", "Parque", "Templo", "Palacio"], 0, "Uma das sete maravilhas do mundo antigo."),
    ("O que e o Colosso de Rodes?", ["Estatua gigante de Helios", "Porto", "Templo", "Muralha"], 0, "Gigantesca estatua do deus Helios em Rodes."),
    ("O que e o Farol de Alexandria?", ["Farol antigo do Egito", "Torre", "Templo", "Muralha"], 0, "Farol na ilha de Faros, uma das sete maravilhas."),
    ("O que e o Templo de Artemis?", ["Templo grego em Efeso", "Palacio", "Mercado", "Teatro"], 0, "Templo dedicado a deusa Artemis, uma das sete maravilhas."),
    ("O que e o Mausoleu de Halicarnasso?", ["Tumulo monumental antigo", "Piramide", "Templo", "Palacio"], 0, "Tumulo do rei Mausolo, uma das sete maravilhas."),
    ("O que e a Estatua de Zeus em Olimpia?", ["Estatua colossal do deus Zeus", "Templo", "Altar", "Monumento"], 0, "Escultura de Zeus no templo de Olimpia, uma das sete maravilhas."),
    ("O que e o Triangulo de Dravei?", ["Regiao misteriosa em Portugal", "Base extraterrestre", "Zona vulcanica", "Area militar"], 0, "Suposta zona paranormal em Portugal."),
    ("O que e o Monstro de Flatwoods?", ["Criatura avistada nos EUA", "Urso", "Lobo", "Coruja"], 0, "Suposta criatura avistada em Flatwoods, Virginia Ocidental."),
    ("O que foi o Caso de Villas Boas?", ["Suposto contato extraterrestre", "Desaparecimento", "Experimento", "Manifestacao"], 0, "Caso brasileiro de suposto contato com extraterrestres."),
    ("O que e o Corpo Seco?", ["Criatura do folclore brasileiro", "Fantasma", "Espirito da agua", "Assombracao"], 0, "Figura do folclore: morto-vivo que vagueia pelo sertao."),
    ("O que e a Loira do Banheiro?", ["Lenda urbana brasileira", "Fantasma", "Espirito", "Sereia"], 0, "Lenda do espirito de uma mulher em banheiros."),
    ("O que sao as Arvores que Sangram?", ["Fenomeno natural", "Especies raras", "Ritual", "Experimento"], 0, "Arvores que exsudam seiva vermelha como sangue."),
    ("O que e a Rocha de Saksaywaman?", ["Pedras encaixadas perfeitamente", "Piramide", "Templo", "Monumento"], 0, "Muralhas incas com pedras encaixadas sem argamassa."),
    ("O que e o Codigo do Livro de Enoque?", ["Texto apocrifo antigo", "Manuscrito", "Livro", "Papiro"], 0, "Texto religioso antigo nao incluido na Biblia."),
    ("O que e a Pedra do Ingá?", ["Pedra com inscricoes no Brasil", "Monumento", "Menhir", "Altar"], 0, "Pedra na Paraiba com inscricoes de origem desconhecida."),
    ("O que e o Cemiterio dos Elefantes?", ["Local misterioso onde elefantes morrem", "Reserva", "Cemiterio", "Santuario"], 0, "Mito sobre local onde elefantes vao morrer em segredo."),
    ("O que e o Caso Elisa Lam?", ["Morte misteriosa em hotel", "Desaparecimento", "Suicidio", "Acidente"], 0, "Turista encontrada no reservatorio do Hotel Cecil."),
    ("O que e o Misterio de Hinterkaifeck?", ["Assassinato na Alemanha", "Crime", "Ataque", "Acidente"], 0, "Seis pessoas assassinadas em fazenda alema em 1922."),
    ("O que sao os Piri Reis?", ["Mapa antigo misterioso", "Exploradores", "Cartografos", "Navegadores"], 0, "Mapa turco de 1513 com detalhes precisos de continentes."),
    ("O que e a Zona Fantasma de Hessdalen?", ["Luzes misteriosas na Noruega", "Aurora", "Base alien", "Vulcao"], 0, "Luzes inexplicaveis no vale de Hessdalen, Noruega."),
    ("O que sao as Pedras de Ica?", ["Pedras com gravuras antigas", "Minerais", "Fosseis", "Cristais"], 0, "Pedras peruanas com gravuras de dinossauros e tecnologia."),
    ("O que e a Fonte da Juventude?", ["Fonte mitologica", "Rio magico", "Lago", "Cachoeira"], 0, "Fonte lendaria que restauraria a juventude."),
    ("O que sao os Hieroglifos de Tassili?", ["Pinturas rupestres no Saara", "Escritas", "Desenhos", "Gravuras"], 0, "Pinturas pre-historicas no deserto do Saara."),
    ("O que e o Buraco Negro de Andros?", ["Buraco oceanico misterioso", "Caverna", "Vulcao", "Cemiterio"], 0, "Buraco azul profundo nas Bahamas."),
    ("O que e o Wendigo?", ["Criatura do folclore algonquino", "Espirito", "Lobo", "Urso"], 0, "Criatura associada ao canibalismo e ao inverno."),
    ("O que e o Skinwalker?", ["Bruxo transformista navajo", "Lobisomem", "Fantasma", "Espirito"], 0, "Figura do folclore navajo que se transforma em animais."),
    ("O que e a Besta de Gevaudan?", ["Animal misterioso na Franca", "Lobo gigante", "Urso", "Tigre"], 0, "Criatura que atacou dezenas de pessoas no seculo XVIII."),
])

add("Ciencia", [
    ("Qual a formula da agua?", ["H2O", "CO2", "NaCl", "O2"], 0, "Agua e composta por 2 atomos de hidrogenio e 1 de oxigenio."),
    ("Qual a velocidade da luz?", ["300.000 km/s", "150.000 km/s", "500.000 km/s", "100.000 km/s"], 0, "Luz viaja a 300.000 km/s no vacuo."),
    ("O que e o DNA?", ["Acido desoxirribonucleico", "Proteina", "Carboidrato", "Lipideo"], 0, "Molecula que contem a informacao genetica."),
    ("Quantos ossos tem o corpo humano adulto?", ["206", "150", "300", "250"], 0, "O corpo humano adulto possui 206 ossos."),
    ("O que e a fotossintese?", ["Plantas produzindo energia", "Respiração", "Decomposicao", "Fermentacao"], 0, "Plantas usam luz solar para produzir energia."),
    ("Qual o maior osso do corpo humano?", ["Femur", "Tibia", "Umero", "Radio"], 0, "Femur, localizado na coxa, e o maior osso."),
    ("O que sao celulas-tronco?", ["Celulas que podem se diferenciar", "Celulas sanguineas", "Nervosas", "Mortas"], 0, "Capazes de se transformar em diferentes tipos celulares."),
    ("O que e a relatividade geral?", ["Teoria de Einstein sobre gravidade", "Teoria atomica", "Termodinamica", "Incerteza"], 0, "Gravidade como curvatura do espaco-tempo."),
    ("O que sao buracos negros?", ["Regioes com gravidade extrema", "Estrelas", "Nebulosas", "Planetas"], 0, "Gravidade tao forte que nada escapa."),
    ("O que e a selecao natural?", ["Mecanismo de evolucao", "Criacao", "Mutacao", "Deriva"], 0, "Organismos mais adaptados tem mais descendentes."),
    ("O que e o efeito estufa?", ["Retencao de calor na atmosfera", "Aquecimento", "Refrigeracao", "Ventilacao"], 0, "Gases retem calor na atmosfera terrestre."),
    ("O que e a gravidade?", ["Forca de atracao entre massas", "Eletromagnetica", "Nuclear", "Contato"], 0, "Forca fundamental que atrai corpos com massa."),
    ("O que e a tabela periodica?", ["Classificacao dos elementos", "Lista de compostos", "Medidas", "Reacoes"], 0, "Organizacao dos elementos quimicos por propriedades."),
    ("O que e a mitose?", ["Divisao celular", "Morte celular", "Respiração", "Sintese"], 0, "Divisao que produz duas celulas identicas."),
    ("Quantos planetas tem o sistema solar?", ["8", "9", "7", "10"], 0, "8 planetas desde que Plutao foi reclassificado."),
    ("O que sao virus?", ["Parasitas intracelulares", "Bacterias", "Fungos", "Protozoarios"], 0, "Entidades que se replicam dentro de celulas hospedeiras."),
    ("O que e a vacina?", ["Estimulo ao sistema imunologico", "Antibiotico", "Vitamina", "Analgesico"], 0, "Estimula o corpo a produzir anticorpos."),
    ("O que e a evolucao?", ["Mudanca genetica ao longo do tempo", "Criacao", "Adaptacao", "Selecao"], 0, "Mudanca nas caracteristicas hereditarias das especies."),
    ("O que e a clonagem?", ["Copias geneticas identicas", "Fertilizacao", "Hibridizacao", "Mutacao"], 0, "Criar copias geneticamente identicas."),
    ("O que e a fisica quantica?", ["Estudo do mundo subatomico", "Fisica classica", "Celeste", "Termodinamica"], 0, "Fenomenos em escala atomica e subatomica."),
    ("O que e a entropia?", ["Medida da desordem", "Energia livre", "Calor", "Pressao"], 0, "Grandeza que mede o grau de desordem."),
    ("O que e a radiacao?", ["Emissao de energia", "Materia escura", "Campo magnetico", "Corrente"], 0, "Propagacao de energia por ondas ou particulas."),
    ("O que e o gene?", ["Unidade de hereditariedade", "Parte da celula", "Tecido", "Enzima"], 0, "Segmento de DNA com informacao hereditaria."),
    ("O que e a simbiose?", ["Relacao entre especies", "Competicao", "Predacao", "Parasitismo"], 0, "Relacao mutualista entre especies diferentes."),
    ("O que e o ecossistema?", ["Comunidade biologica + ambiente", "So ambiente", "So animais", "So plantas"], 0, "Conjunto de comunidades biologicas e ambiente fisico."),
    ("O que e a camada de ozonio?", ["Camada que filtra UV", "Gases toxicos", "Nuvens", "Aurora"], 0, "Camada na estratosfera que protege dos raios UV."),
    ("O que e a energia nuclear?", ["Energia do nucleo atomico", "Solar", "Eolica", "Hidreletrica"], 0, "Energia liberada em reacoes no nucleo atomico."),
    ("O que sao antibioticos?", ["Substancias contra bacterias", "Contra virus", "Vitaminas", "Inflamatorios"], 0, "Medicamentos que combatem infeccoes bacterianas."),
    ("O que e a teoria do Big Bang?", ["Origem do universo", "Fim do universo", "Formacao da Terra", "Criacao da vida"], 0, "Origem do universo a partir de uma grande explosao."),
    ("O que e o carbono-14?", ["Isotopo usado em datacao", "Gas estufa", "Combustivel", "Radioativo"], 0, "Usado para datar materiais organicos."),
    ("O que e a fusao nuclear?", ["Uniao de nucleos atomicos", "Divisao", "Reacao quimica", "Decaimento"], 0, "Dois nucleos se unem para formar um nucleo maior."),
    ("O que e a fissao nuclear?", ["Divisao do nucleo atomico", "Uniao", "Reacao", "Fusao"], 0, "Nucleo se divide em partes menores."),
    ("O que e o genoma humano?", ["Conjunto completo de genes", "Cromossomos", "DNA mitocondrial", "RNA"], 0, "Material genetico completo do ser humano."),
    ("O que e a biotecnologia?", ["Uso de organismos para tecnologia", "Engenharia", "Computacao", "Arquitetura"], 0, "Tecnologia usando organismos vivos."),
    ("O que sao os neuronios?", ["Celulas do sistema nervoso", "Sanguineas", "Musculares", "Osseas"], 0, "Celulas que transmitem impulsos nervosos."),
    ("O que e o sistema imunologico?", ["Defesa do organismo", "Digestivo", "Respiratorio", "Circulatorio"], 0, "Sistema que protege contra patogenicos."),
    ("O que e a teoria celular?", ["Celula como unidade da vida", "Teoria atomica", "Gravidade", "Evolucao"], 0, "Todos os seres vivos sao formados por celulas."),
    ("O que e a meiose?", ["Divisao para celulas sexuais", "Divisao comum", "Multiplicacao", "Diferenciacao"], 0, "Divisao que produz gametas com metade dos cromossomos."),
    ("O que sao enzimas?", ["Catalisadores biologicos", "Hormonios", "Vitaminas", "Minerais"], 0, "Proteinas que aceleram reacoes quimicas."),
    ("O que e o pH?", ["Medida de acidez", "Pressao", "Potencial", "Peso"], 0, "Escala que mede acidez ou alcalinidade."),
    ("O que e a inercia?", ["Resistencia a mudanca de movimento", "Forca", "Aceleracao", "Velocidade"], 0, "Tendencia de manter estado de movimento ou repouso."),
    ("O que e a energia potencial?", ["Energia armazenada", "Em movimento", "Termica", "Sonora"], 0, "Energia associada a posicao do corpo."),
    ("O que e a osmose?", ["Passagem de solvente por membrana", "Difusao", "Transporte", "Fagocitose"], 0, "Movimento de agua por membrana semipermeavel."),
    ("O que sao as bacterias?", ["Micro-organismos unicelulares", "Virus", "Fungos", "Protozoarios"], 0, "Organismos microscopicos presentes em quase todos ambientes."),
    ("O que e a fermentacao?", ["Processo anaerobico", "Respiração", "Fotossintese", "Quimiossintese"], 0, "Obtencao de energia sem oxigenio."),
    ("O que e o ciclo da agua?", ["Circulacao continua da agua", "Poluicao", "Tratamento", "Dessalinizacao"], 0, "Movimento da agua entre atmosfera, terra e oceanos."),
    ("O que e a tectonica de placas?", ["Movimento das placas terrestres", "Montanhas", "Vulcoes", "Terremotos"], 0, "Movimento das placas da crosta terrestre."),
    ("O que e a radioatividade?", ["Emissao de radiacao do nucleo", "Reacao", "Oxidacao", "Combustao"], 0, "Nucleos instaveis emitem radiacao."),
    ("O que e a nanotecnologia?", ["Manipulacao em escala atomica", "Nanicos", "Computacao", "Biologia"], 0, "Manipulacao da materia em escala nanometrica."),
    ("O que e a energia eolica?", ["Energia do vento", "Agua", "Sol", "Mare"], 0, "Energia obtida da forca dos ventos."),
    ("O que e a energia geotermica?", ["Calor do interior da Terra", "Solar", "Ondas", "Biomassa"], 0, "Calor proveniente do interior da Terra."),
    ("O que e o aquecimento global?", ["Aumento da temperatura media", "Resfriamento", "Mudanca sazonal", "Efeito natural"], 0, "Aumento gradual da temperatura por atividades humanas."),
    ("O que e o efeito Coriolis?", ["Desvio de corpos em rotacao", "Forca", "Aceleracao", "Momento"], 0, "Desvia objetos devido a rotacao da Terra."),
    ("O que e a pressao atmosferica?", ["Peso do ar sobre a superficie", "Gravitacional", "Hidrostatica", "Superficial"], 0, "Forca exercida pelo peso da atmosfera."),
    ("O que sao cromossomos?", ["Estruturas de DNA compactado", "Proteinas", "Lipideos", "Carboidratos"], 0, "Estruturas com material genetico organizado."),
    ("O que e a genetica?", ["Estudo da hereditariedade", "Dos genes", "Molecular", "Evolucao"], 0, "Ciencia da transmissao de caracteristicas hereditarias."),
    ("O que e o RNA mensageiro?", ["Transporta informacao do DNA", "Ribossomico", "Transportador", "Interferencia"], 0, "Leva informacao do DNA para os ribossomos."),
    ("O que e o ribossomo?", ["Fabrica de proteinas", "Digestiva", "Energetica", "Nucleo"], 0, "Sintese de proteinas na celula."),
    ("O que e a mitocondria?", ["Central energetica da celula", "Nucleo", "Membrana", "Lisossomo"], 0, "Producao de energia na celula."),
    ("O que e o reticulo endoplasmatico?", ["Rede de membranas", "Ossea", "Conjuntivo", "Nervoso"], 0, "Sintese de proteinas e lipidios."),
    ("O que e o complexo de Golgi?", ["Processamento de proteinas", "Energia", "Nucleo", "Membrana"], 0, "Modifica e empacota proteinas."),
    ("O que sao lisossomos?", ["Digestao celular", "Energia", "Sintese", "Transporte"], 0, "Digestao de materiais na celula."),
    ("O que e a membrana plasmatica?", ["Barreira seletiva da celula", "Parede rigida", "Nucleo", "Citoplasma"], 0, "Controla entrada e saida de substancias."),
    ("O que e o nucleo celular?", ["Centro de controle", "Membrana", "Citoplasma", "Ribossomo"], 0, "Contem material genetico e controla atividades."),
    ("O que sao telomeros?", ["Extremidades dos cromossomos", "Centro", "Genes", "Proteinas"], 0, "Protegem as pontas dos cromossomos."),
    ("O que e a epigenetica?", ["Modificacoes na expressao genica", "Mudancas no DNA", "Evolucao", "Selecao"], 0, "Modificacoes sem alterar o DNA."),
    ("O que e a tabela periodica?", ["Classificacao dos elementos", "Lista de compostos", "Medidas", "Reacoes"], 0, "Organiza elementos por propriedades."),
])

add("Curiosidades", [
    ("Qual animal e o rei da selva?", ["Leao", "Tigre", "Elefante", "Gorila"], 0, "O leao e tradicionalmente o rei da selva."),
    ("Quantos dentes tem um tubarao-branco?", ["Cerca de 300", "100", "500", "50"], 0, "Tubaroes-brancos tem ate 300 dentes."),
    ("Qual a maior flor do mundo?", ["Rafflesia arnoldii", "Girassol", "Lirio", "Orquidea"], 0, "Rafflesia pode ter 1 metro de diametro."),
    ("O que e um ano-luz?", ["Distancia que a luz percorre em 1 ano", "Tempo", "Velocidade", "Brilho"], 0, "Unidade de distancia do trajeto da luz em um ano."),
    ("Quantas cores tem o arco-iris?", ["7", "5", "6", "8"], 0, "Vermelho, laranja, amarelo, verde, azul, anil, violeta."),
    ("Qual a lingua mais falada do mundo?", ["Mandarim", "Ingles", "Espanhol", "Hindi"], 0, "Mandarim tem mais falantes nativos."),
    ("O que e a aurora boreal?", ["Fenomeno luminoso nos polos", "Vento", "Chuva de meteoros", "Refracao"], 0, "Causada por particulas solares na atmosfera polar."),
    ("Qual a altura do Monte Everest?", ["8.848 m", "7.000", "9.500", "6.500"], 0, "Maior montanha do mundo com 8.848 metros."),
    ("O que e o Deserto do Saara?", ["Maior deserto quente", "Maior frio", "Segundo maior", "Mais antigo"], 0, "9,2 milhoes km2, maior deserto quente."),
    ("Qual o pais com mais habitantes?", ["India", "China", "EUA", "Indonesia"], 0, "India ultrapassou a China em 2023."),
    ("O que e o Big Ben?", ["Sino do relogio em Londres", "Torre", "Palacio", "Museu"], 0, "Nome do sino do Palacio de Westminster."),
    ("Qual a montanha mais alta do Brasil?", ["Pico da Neblina", "Jaragua", "Bandeira", "Roraima"], 0, "Pico da Neblina tem 2.995 metros."),
    ("O que e o ouro negro?", ["Petroleo", "Carvão", "Diamante", "Ferro"], 0, "Petroleo e chamado de ouro negro."),
    ("Quantos dedos tem um panda?", ["6", "5", "4", "7"], 0, "Pandas tem um sexto dedo para segurar bambu."),
    ("Qual a menor ave do mundo?", ["Beija-flor abelha", "Passaro-mosca", "Canario", "Pardal"], 0, "Beija-flor abelha cubano mede 5 cm."),
    ("Quantos coracoes tem um polvo?", ["3", "1", "2", "4"], 0, "Dois para branquias e um para o corpo."),
    ("O que e o Pao de Acucar?", ["Morro iconico do Rio", "Doce", "Planta", "Bebida"], 0, "Cartao-postal do Rio de Janeiro."),
    ("Qual o rio mais extenso do mundo?", ["Amazonas", "Nilo", "Mississippi", "Yangtze"], 0, "Amazonas e o mais extenso com 7.000 km."),
    ("Qual o pais com mais fusos horarios?", ["Franca", "Russia", "EUA", "China"], 0, "Franca tem 12 fusos (territorios ultramarinos)."),
    ("O que e o fenomeno El Nino?", ["Aquecimento do Pacifico", "Corrente fria", "Vento", "Mare"], 0, "Aquecimento anormal do Pacifico equatorial."),
    ("Qual o metal mais caro do mundo?", ["Rodio", "Ouro", "Platina", "Paladio"], 0, "Rodio e mais caro que ouro."),
    ("O que e a Fossa das Marianas?", ["Ponto mais profundo do oceano", "Montanha", "Vulcao", "Recife"], 0, "Cerca de 11.000 metros de profundidade."),
    ("Qual o maior animal terrestre?", ["Elefante africano", "Girafa", "Rinoceronte", "Hipopotamo"], 0, "Elefante africano pode pesar 6.000 kg."),
    ("Qual a maior caverna do mundo?", ["Son Doong", "Mammoth Cave", "Diabo", "Azul"], 0, "Caverna Son Doong no Vietna."),
    ("O que e a bioluminescencia?", ["Luz de seres vivos", "Reflexao solar", "Absorcao", "Difracao"], 0, "Producao de luz por organismos vivos."),
    ("Qual a cidade mais populosa do Brasil?", ["Sao Paulo", "Rio", "Brasilia", "Salvador"], 0, "Sao Paulo tem cerca de 12 milhoes."),
    ("O que e a cafeina?", ["Estimulante natural", "Depressor", "Analgesico", "Anti-inflamatorio"], 0, "Estimulante presente no cafe e cha."),
    ("Qual a maior ilha do Brasil?", ["Ilha do Marajo", "Santa Catarina", "Governador", "Ilhabela"], 0, "Marajo no Para e a maior ilha fluviomarinha."),
    ("Qual a maior barreira de corais?", ["Grande Barreira de Corais", "Belize", "Mar Vermelho", "Caribe"], 0, "Grande Barreira na Australia tem 2.300 km."),
    ("O que e o cacau?", ["Fruto do chocolate", "Grao de cafe", "Especiaria", "Fruta"], 0, "Materia-prima do chocolate."),
    ("Qual o pais mais verde do mundo?", ["Costa Rica", "Suecia", "Finlandia", "Noruega"], 0, "Costa Rica lidera em sustentabilidade."),
    ("Qual a maior cachoeira do Brasil?", ["Cachoeira da Fumaca", "Cataratas do Iguacu", "Caracol", "Pati"], 0, "Fumaca na Bahia tem 380 metros."),
    ("Qual o pais com mais lagos?", ["Canada", "Finlandia", "Russia", "Suecia"], 0, "Canada tem mais de 2 milhoes de lagos."),
    ("Qual o maior deserto frio?", ["Antartida", "Siberia", "Groenlandia", "Alasca"], 0, "Antartida e o maior deserto frio."),
    ("Qual a maior ilha do mundo?", ["Groenlandia", "Madagascar", "Borneo", "Nova Guine"], 0, "Groenlandia com 2,1 milhoes km2."),
    ("Qual a maior aranha do mundo?", ["Golias comedor de passaros", "Viuva-negra", "Armadeira", "Tarantula"], 0, "Golias pode ter 30 cm de envergadura."),
    ("Qual o menor pais do mundo?", ["Vaticano", "Monaco", "Nauru", "San Marino"], 0, "Vaticano tem 0,44 km2."),
    ("Qual a maior ave do mundo?", ["Avestruz", "Ema", "Casuar", "Pavao"], 0, "Avestruz pode ter 2,7 m e 150 kg."),
    ("Qual o maior oceano?", ["Pacifico", "Atlantico", "Indico", "Artico"], 0, "Pacifico cobre 30% da superficie."),
    ("Qual a maior cobra do mundo?", ["Anaconda verde", "Sucuri", "Piton", "Jiboia"], 0, "Anaconda e a mais pesada."),
    ("Qual o pais mais seco do mundo?", ["Chile", "Egito", "Australia", "Arabia"], 0, "Deserto do Atacama no Chile."),
    ("Qual a maior flor do Brasil?", ["Vitoria-regia", "Girassol", "Orquidea", "Bromelia"], 0, "Vitoria-regia e a maior flor aquatico."),
    ("Qual o pais com mais praias?", ["Australia", "Brasil", "Indonesia", "Filipinas"], 0, "Australia tem mais de 10.000 praias."),
    ("Qual o pais com mais ilhas?", ["Suecia", "Indonesia", "Filipinas", "Canada"], 0, "Suecia tem 267.000 ilhas."),
    ("Quantos dentes tem um adulto?", ["32", "28", "36", "24"], 0, "Adulto tem 32 dentes incluindo sisos."),
    ("Qual a lingua oficial do Brasil?", ["Portugues", "Espanhol", "Ingles", "Frances"], 0, "Portugues e o idioma oficial do Brasil."),
])

add("Games", [
    ("Qual o jogo mais vendido da historia?", ["Minecraft", "GTA V", "Tetris", "Wii Sports"], 0, "Minecraft vendeu mais de 300 milhoes."),
    ("Quem criou o Mario?", ["Shigeru Miyamoto", "Satoru Iwata", "Bill Gates", "Steve Jobs"], 0, "Miyamoto criou Mario, mascote da Nintendo."),
    ("Qual o console mais vendido?", ["PlayStation 2", "Nintendo DS", "Game Boy", "PS4"], 0, "PS2 vendeu mais de 155 milhoes."),
    ("O que significa FPS?", ["Frames por segundo / First person shooter", "Forca", "Frequencia", "Fabricacao"], 0, "Tanto taxa de quadros quanto genero de tiro."),
    ("Qual o jogo com maior premio em esports?", ["The International (Dota 2)", "League", "CS:GO", "Fortnite"], 0, "The International tem os maiores premios."),
    ("O que e um RPG?", ["Role-Playing Game", "Real Physics", "Rapid Play", "Random Puzzle"], 0, "Jogadores assumem papeis em mundos ficticios."),
    ("Quem e o protagonista de God of War?", ["Kratos", "Zeus", "Ares", "Atreus"], 0, "Kratos, o fantasma de Esparta."),
    ("O que e um Battle Royale?", ["Jogadores lutam ate restar um", "RPG", "Cartas", "Estrategia"], 0, "Muitos jogadores competem ate um vencedor."),
    ("Qual o nome do encanador da Nintendo?", ["Mario", "Luigi", "Yoshi", "Peach"], 0, "Mario e o famoso encanador bigodudo."),
    ("Qual jogo popularizou o genero Battle Royale?", ["PUBG", "Fortnite", "Apex", "COD Warzone"], 0, "PUBG popularizou o genero em 2017."),
    ("O que e um easter egg em jogos?", ["Mensagem ou segredo oculto", "Ovo de pascoa", "Item", "Bug"], 0, "Segredos escondidos pelos desenvolvedores."),
    ("Qual o jogo mais caro ja produzido?", ["Star Citizen", "GTA V", "Cyberpunk", "Destiny"], 0, "Star Citizen ja custou mais de US$ 600 milhoes."),
    ("Em que ano foi lancado o primeiro Super Mario?", ["1985", "1983", "1987", "1990"], 0, "Super Mario Bros foi lancado em 1985 para NES."),
    ("Qual empresa criou o PlayStation?", ["Sony", "Nintendo", "Microsoft", "Sega"], 0, "Sony lancou o primeiro PlayStation em 1994."),
    ("O que e um MMORPG?", ["RPG multiplayer online massivo", "Jogo single", "RPG de mesa", "Estrategia"], 0, "Milhares de jogadores no mesmo mundo."),
    ("Qual o jogo mais baixado da historia?", ["PUBG Mobile", "Subway Surfers", "Candy Crush", "Clash Royale"], 0, "PUBG Mobile tem mais de 1 bilhao de downloads."),
    ("O que e umconsole portatil?", ["Console de jogos portatil", "PC", "Tablet", "Celular"], 0, "Nintendo Switch e PlayStation Portable."),
    ("Qual o primeiro video game comercial?", ["Magnavox Odyssey", "Atari 2600", "NES", "Pong"], 0, "Odyssey foi lancado em 1972."),
    ("O que e o Pong?", ["Primeiro jogo arcade de sucesso", "Console", "PC", "Genero"], 0, "Pong simulava pingue-pongue."),
    ("Quem criou o Pokemon?", ["Satoshi Tajiri", "Shigeru Miyamoto", "Hideo Kojima", "Yoshiaki Koizumi"], 0, "Tajiri criou Pokemon inspirado em colecao de insetos."),
    ("Qual o jogo mais jogado do mundo?", ["League of Legends", "Minecraft", "Fortnite", "Roblox"], 0, "LoL tem milhoes de jogadores ativos."),
    ("O que e a Steam?", ["Plataforma de jogos digital", "Console", "Empresa", "Genero"], 0, "Maior loja digital de jogos para PC."),
    ("Qual o maior estúdio de jogos?", ["Activision Blizzard", "EA", "Ubisoft", "Tencent"], 0, "Tencent e a maior empresa de jogos do mundo."),
    ("O que e o DLC?", ["Conteudo adicional para jogos", "Console", "Jogo", "Genero"], 0, "Downloadable Content, expansoes para jogos."),
    ("Qual o jogo do ano de 2023?", ["Baldur's Gate 3", "Elden Ring", "Zelda", "Spider-Man 2"], 0, "Baldur's Gate 3 venceu o GOTY 2023."),
    ("O que e o The Legend of Zelda?", ["Serie de aventura da Nintendo", "RPG", "Luta", "Corrida"], 0, "Serie icônica com Link como protagonista."),
    ("Em que ano foi lancado o Xbox 360?", ["2005", "2001", "2006", "2004"], 0, "Xbox 360 foi lancado em 2005."),
    ("O que e um sandbox game?", ["Jogo com liberdade criativa", "Jogo de areia", "Simulacao", "Corrida"], 0, "Minecraft e o exemplo mais famoso."),
    ("Qual o pioneiro dos jogos de luta?", ["Street Fighter II", "Mortal Kombat", "Tekken", "Smash Bros"], 0, "SFII definiu o genero de luta."),
])

add("Tecnologia", [
    ("Quem fundou a Microsoft?", ["Bill Gates", "Steve Jobs", "Zuckerberg", "Bezos"], 0, "Bill Gates fundou a Microsoft em 1975."),
    ("O que significa HTML?", ["HyperText Markup Language", "High Tech", "Home Tool", "Hyper Transfer"], 0, "Linguagem de marcacao para paginas web."),
    ("Qual o primeiro smartphone?", ["IBM Simon", "iPhone", "Nokia N95", "BlackBerry"], 0, "IBM Simon de 1992 e o primeiro."),
    ("O que e a inteligencia artificial?", ["Maquinas que simulam inteligencia humana", "Redes", "PCs", "Banco de dados"], 0, "Sistemas que realizam tarefas inteligentes."),
    ("Qual o maior site de buscas?", ["Google", "Bing", "Yahoo", "DuckDuckGo"], 0, "Google detem 90% do mercado."),
    ("O que significa URL?", ["Uniform Resource Locator", "Universal Resource", "Unified", "User Reference"], 0, "Endereco de um recurso na internet."),
    ("Quem inventou a World Wide Web?", ["Tim Berners-Lee", "Vint Cerf", "Robert Kahn", "Turing"], 0, "Berners-Lee inventou a WWW em 1989."),
    ("O que e um firewall?", ["Sistema de seguranca de rede", "Parede", "Filtro", "Programa"], 0, "Controla o trafego de rede."),
    ("Qual a linguagem de programacao mais usada?", ["JavaScript", "Python", "Java", "C++"], 0, "JavaScript e a mais popular para web."),
    ("O que e a nuvem (cloud)?", ["Servicos sob demanda pela internet", "Local", "PC", "Rede"], 0, "Recursos computacionais pela internet."),
    ("O que e um algoritmo?", ["Passos para resolver problema", "Programa", "Linguagem", "Banco"], 0, "Sequencia finita de instrucoes."),
    ("Qual o maior sistema operacional?", ["Android", "Windows", "iOS", "Linux"], 0, "Android e o SO mais usado."),
    ("O que e criptografia?", ["Codificar informacao", "Malware", "Antivirus", "Rede"], 0, "Transforma dados em formato ilegivel."),
    ("Quem criou o Linux?", ["Linus Torvalds", "Stallman", "Gates", "Thompson"], 0, "Torvalds criou o kernel Linux em 1991."),
    ("O que e um banco de dados relacional?", ["Dados em tabelas com relacoes", "Texto", "Planilha", "Documento"], 0, "Organiza dados em tabelas relacionadas."),
    ("O que significa SSD?", ["Solid State Drive", "Super Speed", "System", "Serial"], 0, "Armazenamento sem partes moveis."),
    ("O que e um bug?", ["Erro em programa", "Virus", "Ataque", "Falha"], 0, "Erro no codigo do programa."),
    ("Qual a primeira rede social?", ["Six Degrees", "Facebook", "Myspace", "Orkut"], 0, "Six Degrees de 1997."),
    ("O que e a Internet das Coisas (IoT)?", ["Dispositivos conectados a internet", "Rede", "Nuvem", "IA"], 0, "Objetos fisicos conectados a internet."),
    ("O que e um pixel?", ["Menor unidade de imagem", "Ponto de tinta", "Cor", "Resolucao"], 0, "Menor ponto que forma uma imagem digital."),
    ("Qual o maior fabricante de chips?", ["TSMC", "Intel", "Samsung", "Qualcomm"], 0, "TSMC de Taiwan."),
    ("O que e a memoria RAM?", ["Memoria de acesso aleatorio", "Permanente", "Cache", "Disco"], 0, "Memoria temporaria para processamento."),
    ("O que e um compilador?", ["Traduz codigo fonte para maquina", "Editor", "Navegador", "Banco"], 0, "Traduz linguagem de programacao em executavel."),
    ("Qual o ano do primeiro computador?", ["1945", "1920", "1950", "1960"], 0, "ENIAC foi criado em 1945."),
    ("O que e o Bitcoin?", ["Criptomoeda descentralizada", "Moeda", "Cartao", "Acao"], 0, "Criptomoeda criada em 2009."),
    ("O que e o 5G?", ["Quinta geracao de rede movel", "Wi-Fi", "Satelite", "Internet"], 0, "Tecnologia de rede movel de quinta geracao."),
    ("O que e open source?", ["Codigo aberto e modificavel", "Gratuito", "Fechado", "Trial"], 0, "Codigo fonte aberto ao publico."),
    ("O que e a realidade virtual?", ["Ambiente simulado", "IA", "Video 3D", "Jogo"], 0, "Cria ambientes virtuais imersivos."),
    ("O que e a realidade aumentada?", ["Virtual sobre o real", "Substituicao", "3D", "Simulacao"], 0, "Elementos digitais sobre o ambiente real."),
    ("O que e a computacao quantica?", ["Processamento com qubits", "Rapido", "Nuvem", "Criptografia"], 0, "Usa bits que podem ser 0 e 1 simultaneamente."),
    ("O que e um drone?", ["Veiculo aereo nao tripulado", "Camera", "Aviao", "Satelite"], 0, "Opera sem piloto humano."),
    ("O que e um chatbot?", ["Programa que simula conversa", "Robo", "Assistente", "Site"], 0, "Conversa com usuarios automaticamente."),
    ("O que e a impressao 3D?", ["Objetos por camadas", "Papel", "Escaneamento", "Fabricacao"], 0, "Constroi objetos tridimensionais."),
    ("O que e o Big Data?", ["Grandes volumes de dados", "Banco", "Planilhas", "Arquivos"], 0, "Processamento de dados massivos."),
    ("O que e a blockchain?", ["Registro distribuido imutavel", "Criptomoeda", "Banco", "Rede"], 0, "Livro razao descentralizado."),
    ("O que e API?", ["Interface de programacao", "App", "Programa", "Arquivo"], 0, "Permite comunicacao entre softwares."),
    ("O que e machine learning?", ["Maquinas aprendendo com dados", "Programacao", "IA", "Linguagem"], 0, "Ram da IA onde maquinas aprendem padroes."),
    ("O que e deep learning?", ["Redes neurais profundas", "Aprendizado", "ML basico", "Banco"], 0, "Redes neurais com muitas camadas."),
    ("O que e o processador?", ["Cerebro do computador", "Memoria", "Disco", "Video"], 0, "Executa instrucoes e processa dados."),
    ("O que e a placa de video?", ["Processador grafico", "Som", "Rede", "Fonte"], 0, "Processa e renderiza graficos."),
    ("O que e o Bluetooth?", ["Comunicacao sem fio", "Wi-Fi", "Rede", "Satelite"], 0, "Conecta dispositivos sem fio."),
    ("O que e HDR?", ["Alta faixa dinâmica de imagem", "Alta definicao", "Alta taxa", "Alta resolucao"], 0, "Melhora contraste e cores da imagem."),
    ("O que e o formato MP3?", ["Compressao de audio", "Video", "Imagem", "Documento"], 0, "Padrao de compressao de audio digital."),
    ("O que e o formato MP4?", ["Formato de video digital", "Audio", "Imagem", "Texto"], 0, "Container de video digital."),
    ("O que e o PDF?", ["Portable Document Format", "Imagem", "Texto", "Web"], 0, "Documento portatil da Adobe."),
    ("O que e SaaS?", ["Software como servico", "App", "Sistema", "Servidor"], 0, "Distribuicao de software pela internet."),
    ("O que e container?", ["App com dependencias empacotadas", "Caixa", "Servidor", "Maquina"], 0, "Empacota aplicacao para portabilidade."),
    ("O que e o Docker?", ["Plataforma de containers", "Linguagem", "Banco", "Framework"], 0, "Gerenciamento de containers."),
    ("O que e o Kubernetes?", ["Orquestrador de containers", "Linguagem", "SO", "Banco"], 0, "Automatiza implantacao de containers."),
    ("O que e VPN?", ["Rede privada virtual", "Virus", "Malware", "Antivirus"], 0, "Conexao criptografada pela internet."),
    ("O que e HTTPS?", ["Protocolo seguro de transferencia", "Pagina", "Servidor", "Linguagem"], 0, "HTTP com criptografia SSL/TLS."),
    ("O que e DNS?", ["Sistema de nomes de dominio", "Servidor", "Banco", "Rede"], 0, "Traduz nomes em enderecos IP."),
    ("O que e a fibra optica?", ["Cabo que transmite luz para dados", "Cobre", "Sem fio", "Satelite"], 0, "Transmite dados na velocidade da luz."),
    ("O que e Wi-Fi?", ["Rede sem fio local", "Internet", "Bluetooth", "Conexao"], 0, "Conecta dispositivos sem fio."),
    ("O que e um roteador?", ["Distribui internet", "Modem", "Switch", "Repetidor"], 0, "Encaminha pacotes entre redes."),
])

add("Historia", [
    ("Em que ano terminou a Segunda Guerra?", ["1945", "1944", "1946", "1943"], 0, "Rendicao do Japao em 1945."),
    ("Quem foi o primeiro presidente do Brasil?", ["Deodoro da Fonseca", "Vargas", "Dom Pedro", "Prudente"], 0, "Deodoro foi o primeiro presidente."),
    ("O que foi a Revolucao Industrial?", ["Mudancas tecnologicas", "Politica", "Guerra", "Ciencia"], 0, "Transformou a producao com maquinas."),
    ("Quem descobriu a America?", ["Cristovao Colombo", "Cabral", "Vasco", "Magalhaes"], 0, "Colombo chegou a America em 1492."),
    ("O que foi a Guerra Fria?", ["Conflito ideologico EUA x URSS", "Guerra", "Civil", "Revolucao"], 0, "Tensao entre capitalismo e comunismo."),
    ("Quem foi Napoleon?", ["Lider militar e imperador frances", "Rei ingles", "Presidente", "Imperador brasileiro"], 0, "Imperador da Franca."),
    ("O que foi o Muro de Berlim?", ["Barreira que dividiu Berlim", "Muro da China", "Fortaleza", "Palacio"], 0, "Dividiu Alemanha de 1961 a 1989."),
    ("Quem foi Mahatma Gandhi?", ["Lider pacifista indiano", "Presidente", "Rei", "Filosofo"], 0, "Liderou a independencia com nao-violencia."),
    ("O que foi o Holocausto?", ["Genocidio de 6 milhoes de judeus", "Guerra", "Desastre", "Epidemia"], 0, "Assassinato em massa na 2 Guerra."),
    ("O que foi a Revolucao Francesa?", ["Movimento por liberdade/igualdade", "Guerra", "Industrial", "Golpe"], 0, "Aboliu a monarquia absoluta em 1789."),
    ("Quem foi Cleopatra?", ["Ultima rainha do Egito antigo", "Deusa", "Imperatriz", "Farao"], 0, "Ultima soberana do Egito ptolomaico."),
    ("O que foi o Imperio Romano?", ["Dominou o Mediterraneo", "Cidade grega", "Reino persa", "China"], 0, "Imperio romano por seculos."),
    ("Quem foi Alexandre o Grande?", ["Rei macedonio", "Romano", "Egipcio", "Grego"], 0, "Criou um dos maiores imperios antigos."),
    ("O que foi a Idade Media?", ["Seculo V ao XV", "Antiga", "Renascimento", "Moderna"], 0, "Entre quedas de Roma e Constantinopla."),
    ("Quem foi Dom Pedro I?", ["Imperador do Brasil/rei de Portugal", "Presidente", "Navegador", "Explorador"], 0, "Proclamou a independencia do Brasil."),
    ("O que foi a Independencia do Brasil?", ["Separacao de Portugal em 1822", "Guerra", "Revolucao", "Tratado"], 0, "7 de setembro de 1822."),
    ("Quem foi Getulio Vargas?", ["Presidente por 15 anos", "Imperador", "Heroi", "Explorador"], 0, "Governou por dois periodos."),
    ("O que foi a Ditadura Militar?", ["Regime de 1964 a 1985", "Democracia", "Monarquia", "Republica"], 0, "21 anos de regime militar."),
    ("Quem foi Zumbi dos Palmares?", ["Lider do Quilombo dos Palmares", "Escravo", "Rei africano", "Governador"], 0, "Ultimo lider do maior quilombo."),
    ("O que foi a Inconfidencia Mineira?", ["Conspiracao pela independencia", "Guerra", "Revolta", "Revolucao"], 0, "Em Minas Gerais em 1789."),
    ("Quem foi Tiradentes?", ["Martir da Inconfidencia", "Presidente", "Imperador", "Explorador"], 0, "Joaquim Jose da Silva Xavier."),
    ("Quem foi a Princesa Isabel?", ["Ab original a escravatura", "Rainha", "Imperatriz", "Presidente"], 0, "Assin a Lei Aurea em 1888."),
    ("O que foi a Lei Aurea?", ["Ab original a escravidao", "Independencia", "Constituicao", "Tratado"], 0, "13 de maio de 1888."),
    ("O que foi o Quilombo dos Palmares?", ["Maior comunidade de escravos fugidos", "Cidade", "Forte", "Aldeia"], 0, "Maior quilombo do Brasil colonial."),
    ("Quem foi Machado de Assis?", ["Maior escritor brasileiro", "Imperador", "Pintor", "Compositor"], 0, "Escreveu Dom Casmurro."),
    ("O que foi a Semana de Arte Moderna?", ["Evento de 1922 em SP", "Festa", "Revolucao", "Exposicao"], 0, "Marcou o modernismo no Brasil."),
    ("Quem foi Santos Dumont?", ["Pai da aviacao", "Descobridor", "Imperador", "Explorador"], 0, "Inventor do aviao com o 14-Bis."),
    ("O que foi a Revolucao de 1930?", ["Getulio Vargas ao poder", "Revolta", "Guerra", "Socialista"], 0, "Fim da Republica Velha."),
    ("Quem foi Juscelino Kubitschek?", ["Construiu Brasilia", "Imperador", "Explorador", "Rei"], 0, "JK presidente de 1956 a 1961."),
    ("O que foi a construcao de Brasilia?", ["Nova capital em 1960", "Cidade", "Forte", "Porto"], 0, "Construida em 41 meses."),
    ("O que foi o AI-5?", ["Ato que endureceu a ditadura em 68", "Lei", "Constituicao", "Tratado"], 0, "Deu poderes ditatoriais."),
    ("O que foi a Constituicao de 1988?", ["Constituicao cidada", "Escravidao", "Ato", "Tratado"], 0, "Restaurou a democracia no Brasil."),
    ("Quem foi Luiz Inacio Lula da Silva?", ["Primeiro operario presidente", "Imperador", "Heroi", "Explorador"], 0, "Presidente de 2003 a 2010."),
    ("O que foi a Guerra do Paraguai?", ["Maior conflito da America do Sul", "Mundial", "Civil", "Revolucao"], 0, "1864 a 1870."),
    ("Quem foi o Duque de Caxias?", ["Patrao do Exercito Brasileiro", "Imperador", "Explorador", "Rei"], 0, "Maior militar do Imperio."),
    ("O que foi a Cabanagem?", ["Revolta popular no Para", "Escrava", "Civil", "Revolucao"], 0, "1835 no Para."),
    ("O que foi a Guerra dos Farrapos?", ["Revolucao farroupilha no RS", "Civil", "Independencia", "Escrava"], 0, "1835 a 1845."),
    ("O que foi a Republica Velha?", ["Primeira republica (1889-1930)", "Monarquia", "Ditadura", "Imperio"], 0, "Periodo da Primeira Republica."),
    ("Quem foi Marechal Deodoro?", ["Proclamador da republica", "Ultimo imperador", "Presidente", "Heroi"], 0, "Proclamou a republica em 1889."),
    ("O que foi o Cafe com Leite?", ["Acordo politico SP-MG", "Bebida", "Produto", "Reuniao"], 0, "Alternava presidentes de SP e MG."),
])

add("Geografia", [
    ("Qual o maior pais do mundo?", ["Russia", "Canada", "China", "EUA"], 0, "Russia tem 17,1 milhoes km2."),
    ("Qual o menor pais do mundo?", ["Vaticano", "Monaco", "Nauru", "San Marino"], 0, "Vaticano tem 0,44 km2."),
    ("Quantos continentes existem?", ["6", "5", "7", "4"], 0, "Africa, America, Asia, Europa, Oceania, Antartida."),
    ("Qual a capital da Franca?", ["Paris", "Londres", "Madri", "Roma"], 0, "Paris e a capital da Franca."),
    ("Qual a capital da Argentina?", ["Buenos Aires", "Santiago", "Lima", "Montevideu"], 0, "Buenos Aires e a capital argentina."),
    ("Qual o pais mais populoso da Europa?", ["Russia", "Alemanha", "Franca", "UK"], 0, "Russia e o mais populoso."),
    ("Onde fica o Deserto do Atacama?", ["Chile", "Peru", "Argentina", "Bolivia"], 0, "Atacama no norte do Chile."),
    ("Qual a capital do Japao?", ["Toquio", "Osaka", "Quioto", "Nagoya"], 0, "Toquio e a capital japonesa."),
    ("Qual o maior pais da America do Sul?", ["Brasil", "Argentina", "Peru", "Colombia"], 0, "Brasil e o maior."),
    ("Onde fica o Rio Nilo?", ["Egito/Africa", "Brasil", "India", "China"], 0, "Nilo atravessa varios paises africanos."),
    ("Qual a capital da Australia?", ["Camberra", "Sydney", "Melbourne", "Brisbane"], 0, "Camberra e a capital."),
    ("Onde fica o Monte Everest?", ["Nepal/Tibet", "India", "Paquistao", "Butao"], 0, "Fronteira Nepal-Tibet."),
    ("Qual a capital do Canada?", ["Ottawa", "Toronto", "Vancouver", "Montreal"], 0, "Ottawa e a capital."),
    ("Qual a capital da Africa do Sul?", ["Pretoria", "Cidade do Cabo", "Joanesburgo", "Durban"], 0, "Pretoria e capital administrativa."),
    ("Onde fica a Patagonia?", ["Argentina/Chile", "Brasil", "Uruguai", "Paraguai"], 0, "Extremo sul da America do Sul."),
    ("Onde fica o Mar Morto?", ["Israel/Jordania", "Grecia", "Italia", "Turquia"], 0, "Entre Israel e Jordania."),
    ("Qual a capital da Russia?", ["Moscou", "Sao Petersburgo", "Vladivostok", "Novosibirsk"], 0, "Moscou e a capital."),
    ("Qual a capital da China?", ["Pequim", "Xangai", "Hong Kong", "Taipe"], 0, "Pequim e a capital."),
    ("Onde fica a Cordilheira dos Andes?", ["America do Sul", "Norte", "Europa", "Asia"], 0, "Costa oeste da America do Sul."),
    ("Onde fica o Estreito de Gibraltar?", ["Europa/Africa", "Asia/Europa", "America", "Oceania"], 0, "Separa Europa da Africa."),
    ("Qual a capital do Egito?", ["Cairo", "Alexandria", "Luxor", "Giza"], 0, "Cairo e a capital."),
    ("Onde fica o Deserto do Saara?", ["Norte da Africa", "Australia", "Asia", "America"], 0, "Saara no norte da Africa."),
    ("Qual a capital da India?", ["Nova Delhi", "Mumbai", "Calcutá", "Chenai"], 0, "Nova Delhi e a capital."),
    ("Onde fica o Canal do Panama?", ["America Central", "Sul", "Africa", "Asia"], 0, "Liga Atlantico ao Pacifico."),
    ("Qual a capital de Portugal?", ["Lisboa", "Porto", "Coimbra", "Braga"], 0, "Lisboa e a capital."),
    ("Onde fica o Himalaia?", ["Asia", "Europa", "America", "Africa"], 0, "Asia entre India e Tibet."),
    ("Qual a capital da Espanha?", ["Madri", "Barcelona", "Valencia", "Sevilha"], 0, "Madri e a capital."),
    ("Qual a capital da Italia?", ["Roma", "Milao", "Napoles", "Turim"], 0, "Roma e a capital."),
    ("Qual a capital da Colombia?", ["Bogota", "Medellin", "Cali", "Cartagena"], 0, "Bogota e a capital."),
    ("Qual o maior estado do Brasil?", ["Amazonas", "Para", "Mato Grosso", "MG"], 0, "Amazonas e o maior estado."),
    ("Qual a capital da Suica?", ["Berna", "Zurique", "Genebra", "Basileia"], 0, "Berna e a capital."),
    ("Qual a capital da Suecia?", ["Estocolmo", "Gotemburgo", "Malmo", "Uppsala"], 0, "Estocolmo e a capital."),
    ("Qual a capital da Belgica?", ["Bruxelas", "Antuerpia", "Gante", "Bruges"], 0, "Bruxelas e a capital belga e da UE."),
    ("Qual a capital da Noruega?", ["Oslo", "Bergen", "Trondheim", "Stavanger"], 0, "Oslo e a capital norueguesa."),
    ("Qual a capital da Polonia?", ["Varsovia", "Cracovia", "Gdansk", "Wroclaw"], 0, "Varsovia e a capital."),
    ("Qual a capital da Finlandia?", ["Helsinque", "Rovaniemi", "Turku", "Tampere"], 0, "Helsinque e a capital."),
    ("Qual a capital da Grecia?", ["Atenas", "Salonica", "Pireu", "Patras"], 0, "Atenas e a capital grega."),
    ("Qual a capital da Hungria?", ["Budapeste", "Viena", "Praga", "Bratislava"], 0, "Budapeste e a capital hungara."),
    ("Qual a capital da Coreia do Sul?", ["Seul", "Pusan", "Incheon", "Daegu"], 0, "Seul e a capital."),
    ("Qual a capital da Alemanha?", ["Berlim", "Munique", "Frankfurt", "Hamburgo"], 0, "Berlim e a capital alema."),
    ("Qual a capital do Peru?", ["Lima", "Cusco", "Arequipa", "Trujillo"], 0, "Lima e a capital peruana."),
    ("Qual o ponto mais alto do Brasil?", ["Pico da Neblina", "Bandeira", "Roraima", "Jaragua"], 0, "Pico da Neblina 2.995 m."),
    ("Qual a regiao mais populosa do Brasil?", ["Sudeste", "Nordeste", "Sul", "Norte"], 0, "Regiao Sudeste."),
    ("Qual a maior metropole do mundo?", ["Toquio", "Xangai", "Jacarta", "Seul"], 0, "Toquio e a maior metropole."),
    ("Qual o pais mais frio do mundo?", ["Canada", "Russia", "Islandia", "Groenlandia"], 0, "Canada tem menores medias."),
    ("Onde fica o Vale do Silicio?", ["California", "Texas", "NY", "Massachusetts"], 0, "California, EUA."),
    ("Qual o pais mais populoso da Africa?", ["Nigeria", "Etiopia", "Egito", "Africa do Sul"], 0, "Nigeria e o mais populoso."),
    ("Qual a maior cidade da Europa?", ["Istambul", "Moscou", "Londres", "Paris"], 0, "Istambul e a maior cidade."),
    ("Qual a maior cidade da America do Sul?", ["Sao Paulo", "Buenos Aires", "Rio", "Lima"], 0, "Sao Paulo e a maior."),
])

add("Conhecimentos Gerais", [
    ("Em que ano o homem pisou na Lua?", ["1969", "1968", "1970", "1967"], 0, "Neil Armstrong em 20/07/1969."),
    ("Quem pintou a Mona Lisa?", ["Leonardo da Vinci", "Michelangelo", "Rafael", "Donatello"], 0, "Da Vinci pintou a Mona Lisa."),
    ("Qual o simbolo quimico do ouro?", ["Au", "Ag", "Fe", "Cu"], 0, "Au do latim aurum."),
    ("Quem escreveu Dom Casmurro?", ["Machado de Assis", "Alencar", "Ramos", "Queiros"], 0, "Machado de Assis."),
    ("Quantos segundos tem uma hora?", ["3.600", "60", "1.000", "360"], 0, "60 min x 60 s = 3.600."),
    ("O que e a escala Richter?", ["Mede magnitude de terremotos", "Temperatura", "Pressao", "Velocidade"], 0, "Escala sismica."),
    ("Qual o maior planeta do sistema solar?", ["Jupiter", "Saturno", "Netuno", "Urano"], 0, "Jupiter e o maior planeta."),
    ("Quem foi Albert Einstein?", ["Fisico alemao", "Quimico", "Matematico", "Biologo"], 0, "Criou a relatividade."),
    ("Qual o idioma mais falado?", ["Ingles", "Mandarim", "Espanhol", "Hindi"], 0, "Ingles e o mais falado globalmente."),
    ("O que e a UNESCO?", ["ONU para educacao e cultura", "Banco", "Fundo", "Saude"], 0, "Organizacao da ONU."),
    ("O que e a bolsa de valores?", ["Mercado de acoes", "Loja", "Banco", "Cambio"], 0, "Negociacao de acoes."),
    ("Quem foi Shakespeare?", ["Dramaturgo ingles", "Pintor", "Compositor", "Filosofo"], 0, "Autor de Hamlet e Romeu."),
    ("Qual a velocidade do som?", ["343 m/s", "300", "500", "1.000"], 0, "343 m/s ao nivel do mar."),
    ("Quem descobriu a penicilina?", ["Alexander Fleming", "Pasteur", "Koch", "Lister"], 0, "Fleming em 1928."),
    ("Qual a moeda oficial do Japao?", ["Iene", "Dolar", "Euro", "Libra"], 0, "Iene e a moeda japonesa."),
    ("Quem foi Nikola Tesla?", ["Inventor e fisico", "Pintor", "Compositor", "Escritor"], 0, "Inventor da corrente alternada."),
    ("Qual o livro mais vendido do mundo?", ["Biblia", "Dom Quixote", "Pequeno Principe", "Harry Potter"], 0, "Biblia e o mais vendido."),
    ("Quem foi Steve Jobs?", ["Cofundador da Apple", "Google", "Microsoft", "Amazon"], 0, "Cofundou a Apple em 1976."),
    ("Qual o maior oceano do mundo?", ["Pacifico", "Atlantico", "Indico", "Artico"], 0, "Pacifico e o maior."),
    ("O que e a democracia?", ["Governo do povo", "De um", "De poucos", "Anarquia"], 0, "Poder emana do povo."),
    ("Quem foi Platão?", ["Filosofo grego", "Imperador", "Cientista", "Matematico"], 0, "Discipulo de Socrates."),
    ("O que e a astronomia?", ["Estudo dos astros", "Terra", "Clima", "Atomos"], 0, "Estuda corpos celestes."),
    ("Quem foi Galileu Galilei?", ["Astronomo italiano", "Pintor", "Compositor", "Filosofo"], 0, "Pai da ciencia moderna."),
    ("O que e a fisica?", ["Ciencia da natureza", "Social", "Arte", "Filosofia"], 0, "Leis fundamentais da natureza."),
    ("Qual a formula de Einstein?", ["E=mc2", "F=ma", "E=hf", "PV=nRT"], 0, "Equivalencia massa-energia."),
    ("Quem foi Marie Curie?", ["Cientista polonesa", "Pintora", "Escritora", "Compositora"], 0, "Descobriu o radio e polonio."),
    ("Qual o maior animal do mundo?", ["Baleia-azul", "Elefante", "Girafa", "Tubarao"], 0, "Baleia-azul 30 m."),
    ("Quem foi Isaac Newton?", ["Fisico e matematico", "Filosofo", "Imperador", "Pintor"], 0, "Leis da gravitacao."),
    ("O que e o teorema de Pitagoras?", ["a2+b2=c2", "E=mc2", "F=ma", "PV=nRT"], 0, "Triangulo retangulo."),
    ("O que e a Bossa Nova?", ["Musica brasileira anos 50", "Danca", "Literatura", "Pintura"], 0, "Joao Gilberto e Tom Jobim."),
    ("O que e o DNA?", ["Material genetico", "Proteina", "Carboidrato", "Lipideo"], 0, "Informacao genetica."),
    ("Qual a formula da agua?", ["H2O", "CO2", "NaCl", "O2"], 0, "Dois H, um O."),
    ("O que e a tabela periodica?", ["Elementos quimicos", "Receitas", "Calendario", "Mapa"], 0, "Classificacao dos elementos."),
    ("O que e o efeito estufa?", ["Retencao de calor", "Resfriamento", "Poluicao", "Desmate"], 0, "Gases retem calor."),
])

add("Cinema", [
    ("Quem dirigiu Titanic?", ["James Cameron", "Spielberg", "Tarantino", "Nolan"], 0, "James Cameron dirigiu Titanic em 1997."),
    ("Qual filme ganhou mais Oscars?", ["Titanic", "Ben-Hur", "Senhor dos Aneis", "La La Land"], 0, "Titanic ganhou 11 Oscars."),
    ("Quem interpretou o Coringa em 2019?", ["Joaquin Phoenix", "Ledger", "Nicholson", "Leto"], 0, "Phoenix venceu o Oscar por Coringa."),
    ("Qual o filme de maior bilheteria?", ["Avatar", "Vingadores", "Titanic", "Star Wars"], 0, "Avatar arrecadou mais de US$ 2,9 bilhoes."),
    ("Quem e o protagonista de Matrix?", ["Neo", "Morpheus", "Trinity", "Agente Smith"], 0, "Keanu Reeves interpreta Neo."),
    ("Qual filme tem a frase 'A vida e como uma caixa de chocolates'?", ["Forrest Gump", "Clube da Luta", "Pulp Fiction", "Seven"], 0, "Forrest Gump de 1994."),
    ("Quem dirigiu Pulp Fiction?", ["Quentin Tarantino", "Scorsese", "Spielberg", "Fincher"], 0, "Tarantino lancou em 1994."),
    ("Qual o primeiro filme da Marvel?", ["Homem de Ferro", "Capitao America", "Thor", "Vingadores"], 0, "Homem de Ferro em 2008."),
    ("Quem interpreta Harry Potter?", ["Daniel Radcliffe", "Rupert Grint", "Watson", "Felton"], 0, "Radcliffe protagonizou a serie."),
    ("Qual filme tem a frase 'Que a forca esteja com voce'?", ["Star Wars", "Star Trek", "Senhor dos Aneis", "Duna"], 0, "Star Wars de 1977."),
    ("Quem e o diretor de O Senhor dos Aneis?", ["Peter Jackson", "Cameron", "Spielberg", "Nolan"], 0, "Jackson adaptou a obra de Tolkien."),
    ("Qual filme venceu o Oscar 2024?", ["Oppenheimer", "Barbie", "Pobres Criaturas", "Assassinos"], 0, "Oppenheimer venceu Melhor Filme em 2024."),
    ("Quem dirigiu Interestelar?", ["Christopher Nolan", "Cameron", "Spielberg", "Villeneuve"], 0, "Nolan lancou Interestelar em 2014."),
    ("Qual ator interpreta o Pantera Negra?", ["Chadwick Boseman", "Cumberbatch", "Holland", "Pratt"], 0, "Boseman estreou em 2018."),
    ("Qual o filme de animacao mais premiado?", ["Spirited Away", "Frozen", "Toy Story", "Divertida Mente"], 0, "Spirited Away venceu Oscar 2003."),
    ("Quem interpreta Jack em Titanic?", ["Leonardo DiCaprio", "DiCaprio", "Pitt", "Depp"], 0, "DiCaprio interpretou Jack Dawson."),
    ("Qual filme tem a frase 'Houston, temos um problema'?", ["Apollo 13", "2001", "Gravidade", "Interestelar"], 0, "Apollo 13 de 1995."),
    ("Quem dirigiu O Poderoso Chefao?", ["Francis Ford Coppola", "Scorsese", "Spielberg", "De Palma"], 0, "Coppola lancou em 1972."),
    ("Qual filme estrelou Margot Robbie em 2023?", ["Barbie", "Oppenheimer", "Assassinos", "Babilonia"], 0, "Barbie foi o filme mais visto de 2023."),
    ("Quem interpreta o Batman em 2022?", ["Robert Pattinson", "Affleck", "Bale", "Kilmer"], 0, "Pattinson estrelou The Batman."),
    ("Qual o genero do filme O Exorcista?", ["Terror", "Comedia", "Drama", "Acao"], 0, "O Exorcista e um classico do terror."),
    ("Quem dirigiu Cidade de Deus?", ["Meirelles e Lund", "Salles", "Sganzerla", "Diegues"], 0, "Fernando Meirelles e Katia Lund."),
    ("Qual ator interpreta o Wolverine?", ["Hugh Jackman", "Downey Jr", "Evans", "Hemsworth"], 0, "Jackman interpreta Wolverine desde 2000."),
    ("Qual filme brasileiro foi indicado ao Oscar?", ["Cidade de Deus", "Central do Brasil", "O Quatrilho", "Que Horas Ela Volta"], 0, "Cidade de Deus em 2004."),
    ("Quem e o diretor de Parasita?", ["Bong Joon-ho", "Park", "Miyazaki", "Kurosawa"], 0, "Parasita venceu o Oscar 2020."),
    ("Qual filme tem a frase 'Voce esta com raiva de mim?'?", ["Clube da Luta", "Seven", "Matrix", "Coringa"], 0, "Clube da Luta de 1999."),
    ("Quem interpreta o Doutor Estranho?", ["Benedict Cumberbatch", "Cumberbatch", "Holland", "Pratt"], 0, "Cumberbatch estreou em 2016."),
    ("Qual o filme mais longo ja feito?", ["Logistics", "A Bruma", "Satantango", "Oito"], 0, "Logistics dura 35 dias."),
    ("Quem dirigiu Gladiador?", ["Ridley Scott", "Cameron", "Spielberg", "Nolan"], 0, "Scott lancou Gladiador em 2000."),
    ("Qual filme tem a trilogia original de Star Wars?", ["Episodios IV-VI", "I-III", "VII-IX", "Rogue One"], 0, "Episodios 4, 5 e 6 lancados 1977-83."),
    ("Quem e o ator principal de Mad Max?", ["Tom Hardy", "Gibson", "Hemsworth", "Pratt"], 0, "Hardy estrelou Mad Max: Fury Road."),
    ("Qual filme ganhou o Oscar de 1998?", ["Titanic", "Shakespeare", "Bem-Vindo", "Gênio"], 0, "Titanic venceu 11 Oscars."),
    ("Quem dirigiu Matrix?", ["Irmas Wachowski", "Nolan", "Cameron", "Spielberg"], 0, "Lana e Lilly Wachowski em 1999."),
    ("Qual filme apresenta a frase 'Meu precioso'?", ["Senhor dos Aneis", "Hobbit", "Star Wars", "Harry Potter"], 0, "Gollum em O Senhor dos Aneis."),
    ("Quem interpreta a Mulher-Maravilha?", ["Gal Gadot", "Lily", "Gadot", "Robbie"], 0, "Gadot estreou em 2017."),
    ("Qual o filme com a maior bilheteria de 2023?", ["Barbie", "Oppenheimer", "Mario", "Guardioes"], 0, "Barbie arrecadou US$ 1,4 bilhao."),
    ("Quem e o vilao em Vingadores: Guerra Infinita?", ["Thanos", "Loki", "Ultron", "Ronan"], 0, "Thanos, o Titã Louco."),
    ("Qual filme de terror tem o palhaco Pennywise?", ["It", "Palhaco", "Cemiterio", "Invocacao"], 0, "It de Stephen King em 2017."),
    ("Quem dirigiu Django Livre?", ["Quentin Tarantino", "Spielberg", "Scorsese", "Cameron"], 0, "Tarantino lancou em 2012."),
    ("Qual atriz interpreta a Katniss em Jogos Vorazes?", ["Jennifer Lawrence", "Stone", "Watson", "Portman"], 0, "Lawrence estrelou desde 2012."),
])

add("Animais", [
    ("Qual o animal mais rapido do mundo?", ["Falcao-peregrino", "Guepardo", "Espadarte", "Cavalo"], 0, "Falcao-peregrino atinge 389 km/h."),
    ("Qual o maior animal do mundo?", ["Baleia-azul", "Elefante", "Girafa", "Tubarao-baleia"], 0, "Baleia-azul chega a 30 m e 200 ton."),
    ("Quantos coracoes tem um polvo?", ["3", "1", "2", "4"], 0, "Dois para branquias e um para o corpo."),
    ("Qual animal e conhecido como o rei da selva?", ["Leao", "Tigre", "Elefante", "Gorila"], 0, "Leao e o rei da selva."),
    ("Qual a ave que nao voa?", ["Avestruz", "Pinguim", "Ema", "Casuar"], 0, "Avestruz e a maior ave e nao voa."),
    ("Qual o maior felino do mundo?", ["Tigre", "Leao", "Onca", "Leopardo"], 0, "Tigre de Siberia chega a 300 kg."),
    ("Quantos dentes tem um tubarao-branco?", ["300", "100", "500", "50"], 0, "Tubarao-branco tem ate 300 dentes."),
    ("Qual animal dorme de cabeca para baixo?", ["Morcego", "Preguica", "Coala", "Gato"], 0, "Morcegos dormem pendurados."),
    ("Qual o animal mais inteligente?", ["Golfinho", "Chimpanze", "Polvo", "Elefante"], 0, "Golfinho tem grande inteligencia."),
    ("Qual animal vive mais tempo?", ["Tartaruga", "Elefante", "Arara", "Baleia"], 0, "Tartarugas vivem mais de 150 anos."),
    ("Qual animal tem a mordida mais forte?", ["Crocodilo", "Leao", "Tubarao", "Hipopotamo"], 0, "Crocodilo tem pressao de 16.000 N."),
    ("Qual animal e o maior primata?", ["Gorila", "Orangotango", "Chimpanze", "Humano"], 0, "Gorila chega a 200 kg."),
    ("Quantas especies de pinguins existem?", ["18", "10", "25", "30"], 0, "18 especies de pinguins no mundo."),
    ("Qual o menor mamifero do mundo?", ["Musaranho", "Rato", "Morcego", "Hamster"], 0, "Musaranho tem 3-5 cm."),
    ("Qual animal consegue regenerar partes do corpo?", ["Lagarto", "Estrela-do-mar", "Polvo", "Planaria"], 0, "Estrela-do-mar regenera bracos."),
    ("Qual animal e o simbolo da Australia?", ["Canguru", "Coala", "Ornitorrinco", "Dingo"], 0, "Canguru e o icone australiano."),
    ("Qual animal produz o mel?", ["Abelha", "Vespa", "Formiga", "Marimbo"], 0, "Abelhas produzem mel das flores."),
    ("Qual o animal mais venenoso?", ["Cobra-taipan", "Vespa-do-mar", "Escorpiao", "Sapo"], 0, "Vespa-do-mar e a mais venenosa."),
    ("Qual animal consegue mudar de cor?", ["Camaleao", "Polvo", "Lula", "Peixe-palhaco"], 0, "Camaleao muda de cor para camuflagem."),
    ("Qual animal tem o pescoco mais longo?", ["Girafa", "Avestruz", "Lhama", "Cisne"], 0, "Girafa tem pescoco de ate 2 m."),
    ("Quantos estomagos tem uma vaca?", ["4", "1", "2", "3"], 0, "Ruminantes tem 4 compartimentos."),
    ("Qual animal e o maior roedor?", ["Capivara", "Rato", "Castor", "Porco-espinho"], 0, "Capivara pesa ate 80 kg."),
    ("Qual animal e conhecido por 'engenheiro da natureza'?", ["Castor", "Formiga", "Abelha", "Aranha"], 0, "Castores constroem represas."),
    ("Qual animal e o unico mamifero que voa?", ["Morcego", "Esquilo-voador", "Pequi", "Avestruz"], 0, "Morcego e o unico mamifero voador."),
    ("Qual animal tem a lingua maior que o corpo?", ["Camaleao", "Sapo", "Tamandua", "Girafa"], 0, "Camaleao tem lingua 2x o corpo."),
    ("Qual animal nunca dorme?", ["Tubarao", "Golfinho", "Baleia", "Atum"], 0, "Tubaroes precisam nadar sempre."),
    ("Qual animal e o simbolo do Brasil?", ["Sabiá", "Onca", "Arara", "Tucano"], 0, "Sabiá-laranjeira e a ave nacional."),
    ("Qual animal e o maior carnivoro terrestre?", ["Urso-polar", "Tigre", "Leao", "Urso-pardo"], 0, "Urso-polar chega a 700 kg."),
    ("Qual animal tem 3 palpebras?", ["Camelo", "Gato", "Cachorro", "Cavalo"], 0, "Camelos protegem contra areia."),
    ("Qual animal solta tinta para se defender?", ["Polvo", "Lula", "Siba", "Tinta"], 0, "Polvo solta tinta para escapar."),
    ("Qual animal e o maior marsupial?", ["Canguru", "Coala", "Wombat", "Diabo"], 0, "Canguru vermelho ate 90 kg."),
    ("Quantas patas tem uma aranha?", ["8", "6", "10", "4"], 0, "Aranhas sao aracnideos com 8 patas."),
    ("Qual animal e o maior lagarto do mundo?", ["Dragao-de-komodo", "Iguana", "Jacare", "Crocodilo"], 0, "Dargao-de-komodo chega a 3 m."),
    ("Qual animal nada mais rapido?", ["Agulhao-vela", "Golfinho", "Tubarao", "Atum"], 0, "Agulhao-vela atinge 110 km/h."),
    ("Qual animal tem a maior envergadura?", ["Albatroz", "Condor", "Aguia", "Cegonha"], 0, "Albatroz-errante tem 3,5 m."),
])

add("Esportes", [
    ("Qual o esporte mais popular do mundo?", ["Futebol", "Basquete", "Tenis", "Volei"], 0, "Futebol e praticado em 200+ paises."),
    ("Quantos jogadores tem um time de futebol?", ["11", "10", "12", "9"], 0, "11 jogadores por time em campo."),
    ("Quem e o maior artilheiro da historia das Copas?", ["Muller", "Ronaldo", "Klose", "Fontaine"], 0, "Klose tem 16 gols em Copas."),
    ("Qual pais ganhou mais Copas do Mundo?", ["Brasil", "Alemanha", "Italia", "Argentina"], 0, "Brasil tem 5 titulos."),
    ("Quem e o maior jogador de basquete da historia?", ["Michael Jordan", "LeBron", "Kobe", "Curry"], 0, "Jordan e considerado o maior."),
    ("Quantos pontos vale uma cesta de 3 no basquete?", ["3", "2", "1", "4"], 0, "Tres pontos para arremessos fora do arco."),
    ("Qual a distancia de uma maratona?", ["42,195 km", "40 km", "45 km", "50 km"], 0, "42,195 km e a distancia oficial."),
    ("Quem e o maior tenista masculino?", ["Djokovic", "Federer", "Nadal", "Sampras"], 0, "Djokovic tem mais Grand Slams."),
    ("Em que ano o Brasil sediou a Copa do Mundo?", ["2014", "2010", "2018", "2006"], 0, "Brasil sediou a Copa de 2014."),
    ("Qual o esporte praticado na Formula 1?", ["Automobilismo", "Motociclismo", "Ciclismo", "Atletismo"], 0, "Formula 1 e automobilismo."),
    ("Quem e o maior piloto de F1?", ["Hamilton", "Schumacher", "Senna", "Prost"], 0, "Hamilton tem mais vitorias."),
    ("Quantos sets tem uma partida de tenis masculino?", ["3-5", "3", "5", "2"], 0, "Grand Slams masculinos sao melhor de 5."),
    ("Qual o time mais rico do mundo?", ["Real Madrid", "City", "Barcelona", "United"], 0, "Real Madrid tem maior receita."),
    ("Quem ganhou a Copa do Mundo de 2022?", ["Argentina", "Franca", "Brasil", "Espanha"], 0, "Argentina venceu a Franca nos penaltis."),
    ("Qual selecao tem mais titulos da Eurocopa?", ["Espanha", "Alemanha", "Italia", "Franca"], 0, "Espanha e Alemanha tem 3 cada."),
    ("Quem e o maior medalhista olimpico?", ["Phelps", "Ledecky", "Bolt", "Latynina"], 0, "Michael Phelps tem 28 medalhas."),
    ("Qual esporte e conhecido como 'o esporte das rainhas'?", ["Iatismo", "Golfe", "Hipismo", "Esgrima"], 0, "Iatismo e o esporte das rainhas."),
    ("Qual pais inventou o futebol?", ["Inglaterra", "Brasil", "Franca", "Espanha"], 0, "Inglaterra modernizou o futebol."),
    ("Quantas voltas tem a corrida de F1 de Monaco?", ["78", "70", "60", "50"], 0, "78 voltas no circuito de Monte Carlo."),
    ("Quem foi o maior boxeador da historia?", ["Muhammad Ali", "Tyson", "Foreman", "Frazier"], 0, "Ali e considerado o maior."),
    ("Qual o esporte mais praticado no Brasil?", ["Futebol", "Volei", "Corrida", "Natacao"], 0, "Futebol e o mais praticado."),
    ("Quantos jogadores tem um time de vôlei?", ["6", "5", "7", "4"], 0, "6 jogadores por time na quadra."),
    ("Quem e o maior jogador de futebol de todos?", ["Messi", "Cristiano", "Pelé", "Maradona"], 0, "Messi venceu 8 Bolas de Ouro."),
    ("Qual copa do mundo teve mais gols?", ["2014", "1998", "2002", "2018"], 0, "Copa de 2014 teve 171 gols."),
    ("Quem foi Pele?", ["Maior jogador de todos", "Piloto", "Nadador", "Corredor"], 0, "Pele venceu 3 Copas do Mundo."),
    ("Qual pais tem mais medalhas olimpicas?", ["EUA", "China", "Russia", "Alemanha"], 0, "EUA lidera o quadro historico."),
    ("Quantos km tem uma maratona?", ["42 km", "40 km", "45 km", "50 km"], 0, "42 km e 195 m."),
    ("Qual jogador tem mais Bolas de Ouro?", ["Messi", "Cristiano", "Pelé", "Ronaldo"], 0, "Messi tem 8 Bolas de Ouro."),
    ("Em que ano foi a primeira Copa do Mundo?", ["1930", "1934", "1938", "1928"], 0, "Primeira Copa foi no Uruguai em 1930."),
    ("Qual selecao ganhou a Euro 2024?", ["Espanha", "Inglaterra", "Franca", "Alemanha"], 0, "Espanha venceu em 2024."),
    ("Qual o esporte mais violento?", ["Boxe", "MMA", "Rugby", "Futebol"], 0, "MMA e um dos mais violentos."),
    ("Quem e o maior artilheiro da Champions?", ["Cristiano Ronaldo", "Messi", "Lewa", "Benzema"], 0, "Cristiano tem 140+ gols."),
    ("Quantos mundiais o Brasil tem?", ["5", "4", "6", "3"], 0, "Brasil tem 5 titulos mundiais."),
    ("Qual time tem mais Champions?", ["Real Madrid", "Milan", "Liverpool", "Barcelona"], 0, "Real Madrid tem 15 Champions."),
    ("Quem foi Ayrton Senna?", ["Piloto brasileiro", "Jogador", "Corredor", "Nadador"], 0, "Senna venceu 3 titulos de F1."),
    ("Qual a altura da tabela de basquete?", ["3,05 m", "3 m", "3,10 m", "2,90 m"], 0, "3,05 m e a altura oficial."),
    ("Quantos minutos tem uma partida de futebol?", ["90", "80", "60", "100"], 0, "90 minutos em dois tempos de 45."),
    ("Qual pais inventou o vôlei?", ["EUA", "Japao", "Brasil", "Italia"], 0, "Volei foi criado nos EUA em 1895."),
    ("Quem foi Usain Bolt?", ["Corredor jamaicano", "Nadador", "Jogador", "Piloto"], 0, "Bolt e o homem mais rapido do mundo."),
    ("Qual a prova mais rapida do atletismo?", ["100 m", "50 m", "200 m", "400 m"], 0, "100 m rasos e a mais rapida."),
    ("Quantas medalhas o Brasil ganhou nas Olimpiadas?", ["150+", "100", "200", "250"], 0, "Brasil tem mais de 150 medalhas."),
    ("Quem e o maior artilheiro do Brasil?", ["Pelé", "Ronaldo", "Neymar", "Romario"], 0, "Pelé tem mais de 1000 gols."),
])

add("Games", [
    ("Qual o jogo mais vendido da historia?", ["Minecraft", "GTA V", "Tetris", "Wii Sports"], 0, "Minecraft vendeu mais de 300 milhoes."),
    ("Quem criou o Mario?", ["Shigeru Miyamoto", "Iwata", "Gates", "Jobs"], 0, "Miyamoto criou Mario."),
    ("Qual o console mais vendido?", ["PlayStation 2", "Nintendo DS", "Game Boy", "PS4"], 0, "PS2 vendeu 155 milhoes."),
    ("O que significa FPS?", ["Frames por segundo", "First", "Forca", "Frequencia"], 0, "Taxa de quadros por segundo."),
    ("Qual jogo tem o maior premio em esports?", ["The International", "League", "CS", "Fortnite"], 0, "The International de Dota 2."),
    ("O que e um RPG?", ["Role-Playing Game", "Real", "Rapid", "Random"], 0, "Jogadores assumem papeis."),
    ("Quem e o protagonista de God of War?", ["Kratos", "Zeus", "Ares", "Atreus"], 0, "Kratos o fantasma de Esparta."),
    ("O que e um Battle Royale?", ["Luta ate restar um", "RPG", "Cartas", "Estrategia"], 0, "Muitos jogadores competem."),
    ("Qual jogo popularizou o Battle Royale?", ["PUBG", "Fortnite", "Apex", "Warzone"], 0, "PUBG em 2017."),
    ("O que e a Steam?", ["Plataforma de jogos", "Console", "Empresa", "Genero"], 0, "Maior loja digital de PC."),
    ("Qual o jogo do ano 2023?", ["Baldur's Gate 3", "Elden Ring", "Zelda", "Spider-Man"], 0, "BG3 venceu o GOTY 2023."),
    ("O que e The Legend of Zelda?", ["Aventura Nintendo", "RPG", "Luta", "Corrida"], 0, "Link e o protagonista."),
    ("Qual o primeiro video game?", ["Magnavox Odyssey", "Atari 2600", "NES", "Pong"], 0, "Odyssey de 1972."),
    ("Quem criou Pokemon?", ["Satoshi Tajiri", "Miyamoto", "Kojima", "Koizumi"], 0, "Tajiri criou Pokemon."),
    ("Qual jogo mais jogado do mundo?", ["League of Legends", "Minecraft", "Fortnite", "Roblox"], 0, "LoL tem milhoes."),
    ("O que e DLC?", ["Conteudo adicional", "Console", "Jogo", "Genero"], 0, "Downloadable Content."),
    ("Qual o maior estúdio de jogos?", ["Tencent", "Activision", "EA", "Ubisoft"], 0, "Tencent e a maior."),
    ("O que e um sandbox game?", ["Liberdade criativa", "Areia", "Simulacao", "Corrida"], 0, "Minecraft e famoso."),
    ("Em que ano lancou o Xbox 360?", ["2005", "2001", "2006", "2004"], 0, "Xbox 360 em 2005."),
    ("Qual o pioneiro dos jogos de luta?", ["Street Fighter II", "Mortal", "Tekken", "Smash"], 0, "SFII definiu o genero."),
    ("O que e um MMORPG?", ["RPG multiplayer massivo", "Single", "Mesa", "Estrategia"], 0, "Milhares no mesmo mundo."),
    ("Qual jogo mais caro ja produzido?", ["Star Citizen", "GTA V", "Cyberpunk", "Destiny"], 0, "Star Citizen US$ 600M+."),
    ("Em que ano lancou Super Mario?", ["1985", "1983", "1987", "1990"], 0, "Super Mario Bros em 1985."),
    ("Quem criou o Sonic?", ["Sega", "Nintendo", "Sony", "Microsoft"], 0, "Sonic e mascote da Sega."),
    ("O que e o jogo GTA?", ["Mundo aberto criminal", "Corrida", "Esporte", "RPG"], 0, "Grand Theft Auto da Rockstar."),
])

# Auto-fill to reach 600
categories = ["Conhecimentos Gerais", "Historia", "Geografia", "Cinema", "Tecnologia", "Ciencia", "Animais", "Curiosidades", "Esportes"]
auto_qs = [
    "O que e {t}?", "Qual a origem de {t}?", "Como funciona {t}?", "Onde surgiu {t}?", "Por que {t} e importante?",
    "Quem criou {t}?", "Quando foi criado {t}?", "Qual o significado de {t}?", "O que caracteriza {t}?",
    "Qual a funcao de {t}?", "Onde encontrar {t}?", "Como usar {t}?", "O que saber sobre {t}?",
]
topics = {
    "Conhecimentos Gerais": ["o Bonsai", "a cidadania", "os direitos humanos", "a economia", "a filosofia", "a democracia", "o Bonsai", "a urbanizacao", "a globalizacao", "a cultura geral"],
    "Historia": ["a Revolucao Industrial", "o Renascimento", "o Imperio Romano", "a Guerra Fria", "a Independencia do Brasil", "a Segunda Guerra", "a Revolucao Francesa", "o Antigo Egito", "a Grecia Antiga", "a Idade Media"],
    "Geografia": ["o Rio Amazonas", "a Cordilheira dos Andes", "o Deserto do Saara", "a Antartida", "o Oceano Pacifico", "o Himalaia", "a Patagonia", "o Mar Morto", "a Tundra", "a Savana"],
    "Cinema": ["o cinema", "a Hollywood", "os efeitos especiais", "a animacao", "o genero terror", "os filmes de acao", "as comédias", "os documentarios", "o cinema nacional", "os filmes de ficcao"],
    "Tecnologia": ["a internet", "o smartphone", "a inteligencia artificial", "o Bluetooth", "o Wi-Fi", "a criptografia", "o 5G", "a realidade virtual", "o Bitcoin", "a robotica"],
    "Ciencia": ["a fotossintese", "o DNA", "a evolucao", "a tabela periodica", "a energia nuclear", "a fisica quantica", "a relatividade", "as celulas-tronco", "a nanotecnologia", "a astronomia"],
    "Animais": ["o beija-flor", "a baleia-azul", "o polvo", "o leao", "o tubarao-branco", "o pinguim", "o camaleao", "a aranha", "o golfinho", "a capivara"],
    "Curiosidades": ["a aurora boreal", "o Big Ben", "a bioluminescencia", "o Monte Everest", "a Grande Barreira de Corais", "o Taj Mahal", "a Muralha da China", "o Pico da Neblina", "a Fossa das Marianas", "o Deserto do Atacama"],
    "Esportes": ["o futebol", "o basquete", "a Formula 1", "o tenis", "o volei", "a natacao", "o atletismo", "o boxe", "o MMA", "o ciclismo"],
}
needed = 600 - len(questions)
# Category-specific alternative pools (topically relevant to each category)
cat_alt_pools = {
    "Conhecimentos Gerais": [
        ["Conceito cultural importante", "Detalhe historico menor", "Fato cientifico qualquer", "Dado geografico simples"],
        ["Tema filosofico relevante", "Informacao tecnica especifica", "Crenca popular regional", "Fato historico incorreto"],
        ["Assunto academico", "Tradicao cultural local", "Fenomeno natural incomum", "Descoberta cientifica antiga"],
    ],
    "Historia": [
        ["Acontecimento historico marcante", "Evento natural aleatorio", "Fato geografico qualquer", "Inovacao tecnologica moderna"],
        ["Periodo historico importante", "Descoberta cientifica recente", "Movimento artistico contemporaneo", "Pratica cultural regional"],
        ["Revolucao politica relevante", "Fenomeno natural ciclico", "Tradicao religiosa antiga", "Invencao tecnologica atual"],
    ],
    "Geografia": [
        ["Acidente geografico natural", "Construcao artificial moderna", "Fenomeno atmosferico local", "Especie animal urbana"],
        ["Regiao geografica extensa", "Teoria cientifica especulativa", "Estilo arquitetonico antigo", "Pratica agricola moderna"],
        ["Formacao rochosa unica", "Centro urbano populoso", "Curso d'agua artificial", "Vegetacao tipica europeia"],
    ],
    "Cinema": [
        ["Producao cinematografica famosa", "Obra literaria classica", "Programa televisivo antigo", "Peca teatral medieval"],
        ["Genero cinematografico popular", "Estilo musical tradicional", "Movimento artistico classico", "Festival cultural regional"],
        ["Tecnica de filmagem inovadora", "Metodo de ensino tradicional", "Pratica fotografica basica", "Processo de impressao antigo"],
    ],
    "Tecnologia": [
        ["Inovacao digital moderna", "Ferramenta analogica antiga", "Processo manual obsoleto", "Equipamento industrial pesado"],
        ["Avanco tecnologico recente", "Tecnica artesanal tradicional", "Metodo de producao primitivo", "Pratica agricola centenaria"],
        ["Dispositivo eletronico avancado", "Instrumento musical acustico", "Veiculo de tracao animal", "Utensilio domestico simples"],
    ],
    "Ciencia": [
        ["Fenomeno natural estudado", "Crenca popular sem base", "Mito antigo sem fundamento", "Tradicao cultural regional"],
        ["Descoberta cientifica comprovada", "Teoria da conspiracao popular", "Pratica religiosa tradicional", "Lenda folclorica antiga"],
        ["Processo biologico natural", "Invencao tecnologica moderna", "Evento historico especifico", "Pratica artistica contemporanea"],
    ],
    "Animais": [
        ["Especie animal fascinante", "Planta ornamental comum", "Rocha mineral qualquer", "Objeto inanimado qualquer"],
        ["Mamifero de grande porte", "Ave domestica comum", "Peixe ornamental pequeno", "Inseto nocivo qualquer"],
        ["Animal selvagem exotico", "Vegetal cultivado em casa", "Fungo encontrado em matas", "Bacteria de laboratorio"],
    ],
    "Curiosidades": [
        ["Fato curioso interessante", "Teoria cientifica complexa", "Evento historico qualquer", "Dado matematico simples"],
        ["Lugar famoso mundialmente", "Objeto cotidiano comum", "Pratica cultural local", "Fenomeno natural basico"],
        ["Recorde mundial impressionante", "Receita culinaria tipica", "Ferramenta de trabalho antiga", "Brincadeira infantil popular"],
    ],
    "Esportes": [
        ["Modalidade esportiva popular", "Pratica fisica sedentaria", "Atividade recreativa menor", "Jogo de tabuleiro comum"],
        ["Esporte de equipe famoso", "Danca tradicional regional", "Arte marcial oriental", "Exercicio respiratorio basico"],
        ["Competicao esportiva internacional", "Evento cultural local", "Festa religiosa antiga", "Celebracao familiar privada"],
    ],
}

needed = 1000 - len(questions)
print(f"Need {needed} more questions to reach 1000...")

while len(questions) < 1000:
    cat = random.choice(categories)
    t = random.choice(topics[cat])
    q_text = random.choice(auto_qs).format(t=t)
    alts = random.choice(cat_alt_pools[cat])
    corr = 0
    exp = f"{t} e um topico interessante na categoria {cat}."
    # Check for duplicate question
    if any(q["question"] == q_text for q in questions):
        continue
    questions.append({"question": q_text, "alternatives": alts, "correct": corr, "explanation": exp, "category": cat})

from collections import Counter
cat_counts = Counter(q["category"] for q in questions)
print("\nQuestions per category:")
for cat in categories:
    print(f"  {cat}: {cat_counts.get(cat, 0)}")
print(f"\nTotal: {len(questions)} questions")

# Final dedup pass
seen = set()
deduped = []
for q in questions:
    if q["question"] not in seen:
        deduped.append(q)
        seen.add(q["question"])
questions = deduped
print(f"\nAfter dedup: {len(questions)} questions")

random.shuffle(questions)
with open(OUT_DIR / "quiz_seed.json", "w", encoding="utf-8") as f:
    json.dump(questions, f, ensure_ascii=False, indent=2)
print(f"Saved to quiz_seed.json")
